// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "HIROController.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



void
CommonCommands::RETURN_ID::operator>>= (cdrStream &_n) const
{
  id >>= _n;
  _n.marshalString(comment,0);

}

void
CommonCommands::RETURN_ID::operator<<= (cdrStream &_n)
{
  (::CORBA::Long&)id <<= _n;
  comment = _n.unmarshalString(0);

}

CommonCommands_ptr CommonCommands_Helper::_nil() {
  return ::CommonCommands::_nil();
}

::CORBA::Boolean CommonCommands_Helper::is_nil(::CommonCommands_ptr p) {
  return ::CORBA::is_nil(p);

}

void CommonCommands_Helper::release(::CommonCommands_ptr p) {
  ::CORBA::release(p);
}

void CommonCommands_Helper::marshalObjRef(::CommonCommands_ptr obj, cdrStream& s) {
  ::CommonCommands::_marshalObjRef(obj, s);
}

CommonCommands_ptr CommonCommands_Helper::unmarshalObjRef(cdrStream& s) {
  return ::CommonCommands::_unmarshalObjRef(s);
}

void CommonCommands_Helper::duplicate(::CommonCommands_ptr obj) {
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
}

CommonCommands_ptr
CommonCommands::_duplicate(::CommonCommands_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
  return obj;
}

CommonCommands_ptr
CommonCommands::_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


CommonCommands_ptr
CommonCommands::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

CommonCommands_ptr
CommonCommands::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_CommonCommands _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_CommonCommands* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_CommonCommands;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* CommonCommands::_PD_repoId = "IDL:CommonCommands:1.0";


_objref_CommonCommands::~_objref_CommonCommands() {
  
}


_objref_CommonCommands::_objref_CommonCommands(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::CommonCommands::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
_objref_CommonCommands::_ptrToObjRef(const char* id)
{
  if( id == ::CommonCommands::_PD_repoId )
    return (::CommonCommands_ptr) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::CommonCommands::_PD_repoId) )
    return (::CommonCommands_ptr) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Proxy call descriptor class. Mangled signature:
//  _cCommonCommands_mRETURN__ID
class _0RL_cd_7ac480c4252a17cd_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_7ac480c4252a17cd_00000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  CommonCommands::RETURN_ID_var result;
};

void _0RL_cd_7ac480c4252a17cd_00000000::marshalReturnedValues(cdrStream& _n)
{
  (const CommonCommands::RETURN_ID&) result >>= _n;

}

void _0RL_cd_7ac480c4252a17cd_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new CommonCommands::RETURN_ID;
  (CommonCommands::RETURN_ID&)result <<= _n;

}

const char* const _0RL_cd_7ac480c4252a17cd_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_7ac480c4252a17cd_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_7ac480c4252a17cd_00000000* tcd = (_0RL_cd_7ac480c4252a17cd_00000000*)cd;
  _impl_CommonCommands* impl = (_impl_CommonCommands*) svnt->_ptrToInterface(CommonCommands::_PD_repoId);
  tcd->result = impl->servoOFF();


}

CommonCommands::RETURN_ID* _objref_CommonCommands::servoOFF()
{
  _0RL_cd_7ac480c4252a17cd_00000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_10000000, "servoOFF", 9);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Local call call-back function.
static void
_0RL_lcfn_7ac480c4252a17cd_20000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_7ac480c4252a17cd_00000000* tcd = (_0RL_cd_7ac480c4252a17cd_00000000*)cd;
  _impl_CommonCommands* impl = (_impl_CommonCommands*) svnt->_ptrToInterface(CommonCommands::_PD_repoId);
  tcd->result = impl->servoON();


}

CommonCommands::RETURN_ID* _objref_CommonCommands::servoON()
{
  _0RL_cd_7ac480c4252a17cd_00000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_20000000, "servoON", 8);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Local call call-back function.
static void
_0RL_lcfn_7ac480c4252a17cd_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_7ac480c4252a17cd_00000000* tcd = (_0RL_cd_7ac480c4252a17cd_00000000*)cd;
  _impl_CommonCommands* impl = (_impl_CommonCommands*) svnt->_ptrToInterface(CommonCommands::_PD_repoId);
  tcd->result = impl->servoOFFArm();


}

CommonCommands::RETURN_ID* _objref_CommonCommands::servoOFFArm()
{
  _0RL_cd_7ac480c4252a17cd_00000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_30000000, "servoOFFArm", 12);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Local call call-back function.
static void
_0RL_lcfn_7ac480c4252a17cd_40000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_7ac480c4252a17cd_00000000* tcd = (_0RL_cd_7ac480c4252a17cd_00000000*)cd;
  _impl_CommonCommands* impl = (_impl_CommonCommands*) svnt->_ptrToInterface(CommonCommands::_PD_repoId);
  tcd->result = impl->servoOFFHand();


}

CommonCommands::RETURN_ID* _objref_CommonCommands::servoOFFHand()
{
  _0RL_cd_7ac480c4252a17cd_00000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_40000000, "servoOFFHand", 13);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Local call call-back function.
static void
_0RL_lcfn_7ac480c4252a17cd_50000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_7ac480c4252a17cd_00000000* tcd = (_0RL_cd_7ac480c4252a17cd_00000000*)cd;
  _impl_CommonCommands* impl = (_impl_CommonCommands*) svnt->_ptrToInterface(CommonCommands::_PD_repoId);
  tcd->result = impl->servoONArm();


}

CommonCommands::RETURN_ID* _objref_CommonCommands::servoONArm()
{
  _0RL_cd_7ac480c4252a17cd_00000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_50000000, "servoONArm", 11);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Local call call-back function.
static void
_0RL_lcfn_7ac480c4252a17cd_60000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_7ac480c4252a17cd_00000000* tcd = (_0RL_cd_7ac480c4252a17cd_00000000*)cd;
  _impl_CommonCommands* impl = (_impl_CommonCommands*) svnt->_ptrToInterface(CommonCommands::_PD_repoId);
  tcd->result = impl->servoONHand();


}

CommonCommands::RETURN_ID* _objref_CommonCommands::servoONHand()
{
  _0RL_cd_7ac480c4252a17cd_00000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_60000000, "servoONHand", 12);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
_pof_CommonCommands::~_pof_CommonCommands() {}


omniObjRef*
_pof_CommonCommands::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::_objref_CommonCommands(ior, id);
}


::CORBA::Boolean
_pof_CommonCommands::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::CommonCommands::_PD_repoId) )
    return 1;
  
  return 0;
}

const _pof_CommonCommands _the_pof_CommonCommands;

_impl_CommonCommands::~_impl_CommonCommands() {}


::CORBA::Boolean
_impl_CommonCommands::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "servoOFF") ) {

    _0RL_cd_7ac480c4252a17cd_00000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_10000000, "servoOFF", 9, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "servoON") ) {

    _0RL_cd_7ac480c4252a17cd_00000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_20000000, "servoON", 8, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "servoOFFArm") ) {

    _0RL_cd_7ac480c4252a17cd_00000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_30000000, "servoOFFArm", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "servoOFFHand") ) {

    _0RL_cd_7ac480c4252a17cd_00000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_40000000, "servoOFFHand", 13, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "servoONArm") ) {

    _0RL_cd_7ac480c4252a17cd_00000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_50000000, "servoONArm", 11, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "servoONHand") ) {

    _0RL_cd_7ac480c4252a17cd_00000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_60000000, "servoONHand", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
_impl_CommonCommands::_ptrToInterface(const char* id)
{
  if( id == ::CommonCommands::_PD_repoId )
    return (::_impl_CommonCommands*) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::CommonCommands::_PD_repoId) )
    return (::_impl_CommonCommands*) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
_impl_CommonCommands::_mostDerivedRepoId()
{
  return ::CommonCommands::_PD_repoId;
}

void
MotionCommands::CarPosWithElbow::operator>>= (cdrStream &_n) const
{
  
#ifndef OMNI_MIXED_ENDIAN_DOUBLE
  if (! _n.marshal_byte_swap()) {
    _n.put_octet_array((_CORBA_Octet*)(carPos),96,omni::ALIGN_8);
  }
  else 
#endif
  {
    _n.declareArrayLength(omni::ALIGN_8, 96);
    for (_CORBA_ULong _0i0 = 0; _0i0 < 3; _0i0++){
      for (_CORBA_ULong _0i1 = 0; _0i1 < 4; _0i1++){
        carPos[_0i0][_0i1] >>= _n;
      }
    }
  }
  elbow >>= _n;
  structFlag >>= _n;

}

void
MotionCommands::CarPosWithElbow::operator<<= (cdrStream &_n)
{
  _n.unmarshalArrayDouble((_CORBA_Double*)(carPos), 12);
  (::CORBA::Double&)elbow <<= _n;
  (ULONG&)structFlag <<= _n;

}

void
MotionCommands::RETURN_ID::operator>>= (cdrStream &_n) const
{
  id >>= _n;
  _n.marshalString(comment,0);

}

void
MotionCommands::RETURN_ID::operator<<= (cdrStream &_n)
{
  (::CORBA::Long&)id <<= _n;
  comment = _n.unmarshalString(0);

}

MotionCommands_ptr MotionCommands_Helper::_nil() {
  return ::MotionCommands::_nil();
}

::CORBA::Boolean MotionCommands_Helper::is_nil(::MotionCommands_ptr p) {
  return ::CORBA::is_nil(p);

}

void MotionCommands_Helper::release(::MotionCommands_ptr p) {
  ::CORBA::release(p);
}

void MotionCommands_Helper::marshalObjRef(::MotionCommands_ptr obj, cdrStream& s) {
  ::MotionCommands::_marshalObjRef(obj, s);
}

MotionCommands_ptr MotionCommands_Helper::unmarshalObjRef(cdrStream& s) {
  return ::MotionCommands::_unmarshalObjRef(s);
}

void MotionCommands_Helper::duplicate(::MotionCommands_ptr obj) {
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
}

MotionCommands_ptr
MotionCommands::_duplicate(::MotionCommands_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
  return obj;
}

MotionCommands_ptr
MotionCommands::_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


MotionCommands_ptr
MotionCommands::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

MotionCommands_ptr
MotionCommands::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_MotionCommands _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_MotionCommands* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_MotionCommands;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* MotionCommands::_PD_repoId = "IDL:MotionCommands:1.0";


_objref_MotionCommands::~_objref_MotionCommands() {
  
}


_objref_MotionCommands::_objref_MotionCommands(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::MotionCommands::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
_objref_MotionCommands::_ptrToObjRef(const char* id)
{
  if( id == ::MotionCommands::_PD_repoId )
    return (::MotionCommands_ptr) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::MotionCommands::_PD_repoId) )
    return (::MotionCommands_ptr) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Proxy call descriptor class. Mangled signature:
//  _cMotionCommands_mRETURN__ID
class _0RL_cd_7ac480c4252a17cd_70000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_7ac480c4252a17cd_70000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  MotionCommands::RETURN_ID_var result;
};

void _0RL_cd_7ac480c4252a17cd_70000000::marshalReturnedValues(cdrStream& _n)
{
  (const MotionCommands::RETURN_ID&) result >>= _n;

}

void _0RL_cd_7ac480c4252a17cd_70000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new MotionCommands::RETURN_ID;
  (MotionCommands::RETURN_ID&)result <<= _n;

}

const char* const _0RL_cd_7ac480c4252a17cd_70000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_7ac480c4252a17cd_80000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_7ac480c4252a17cd_70000000* tcd = (_0RL_cd_7ac480c4252a17cd_70000000*)cd;
  _impl_MotionCommands* impl = (_impl_MotionCommands*) svnt->_ptrToInterface(MotionCommands::_PD_repoId);
  tcd->result = impl->closeGripper();


}

MotionCommands::RETURN_ID* _objref_MotionCommands::closeGripper()
{
  _0RL_cd_7ac480c4252a17cd_70000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_80000000, "closeGripper", 13);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Proxy call descriptor class. Mangled signature:
//  _cMotionCommands_mRETURN__ID_i_cMotionCommands_mDoubleSeq_i_cMotionCommands_mDoubleSeq
class _0RL_cd_7ac480c4252a17cd_90000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_7ac480c4252a17cd_90000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  MotionCommands::DoubleSeq_var arg_0_;
  const MotionCommands::DoubleSeq* arg_0;
  MotionCommands::DoubleSeq_var arg_1_;
  const MotionCommands::DoubleSeq* arg_1;
  MotionCommands::RETURN_ID_var result;
};

void _0RL_cd_7ac480c4252a17cd_90000000::marshalArguments(cdrStream& _n)
{
  (const MotionCommands::DoubleSeq&) *arg_0 >>= _n;
  (const MotionCommands::DoubleSeq&) *arg_1 >>= _n;

}

void _0RL_cd_7ac480c4252a17cd_90000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = new MotionCommands::DoubleSeq;
  (MotionCommands::DoubleSeq&)arg_0_ <<= _n;
  arg_0 = &arg_0_.in();
  arg_1_ = new MotionCommands::DoubleSeq;
  (MotionCommands::DoubleSeq&)arg_1_ <<= _n;
  arg_1 = &arg_1_.in();

}

void _0RL_cd_7ac480c4252a17cd_90000000::marshalReturnedValues(cdrStream& _n)
{
  (const MotionCommands::RETURN_ID&) result >>= _n;

}

void _0RL_cd_7ac480c4252a17cd_90000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new MotionCommands::RETURN_ID;
  (MotionCommands::RETURN_ID&)result <<= _n;

}

const char* const _0RL_cd_7ac480c4252a17cd_90000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_7ac480c4252a17cd_a0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_7ac480c4252a17cd_90000000* tcd = (_0RL_cd_7ac480c4252a17cd_90000000*)cd;
  _impl_MotionCommands* impl = (_impl_MotionCommands*) svnt->_ptrToInterface(MotionCommands::_PD_repoId);
  tcd->result = impl->moveGripper(*tcd->arg_0, *tcd->arg_1);


}

MotionCommands::RETURN_ID* _objref_MotionCommands::moveGripper(const ::MotionCommands::DoubleSeq& r_angle, const ::MotionCommands::DoubleSeq& l_angle)
{
  _0RL_cd_7ac480c4252a17cd_90000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_a0000000, "moveGripper", 12);
  _call_desc.arg_0 = &(::MotionCommands::DoubleSeq&) r_angle;
  _call_desc.arg_1 = &(::MotionCommands::DoubleSeq&) l_angle;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Proxy call descriptor class. Mangled signature:
//  _cMotionCommands_mRETURN__ID_i_cMotionCommands_mCarPosWithElbow_i_cMotionCommands_mCarPosWithElbow
class _0RL_cd_7ac480c4252a17cd_b0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_7ac480c4252a17cd_b0000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  MotionCommands::CarPosWithElbow arg_0_;
  const MotionCommands::CarPosWithElbow* arg_0;
  MotionCommands::CarPosWithElbow arg_1_;
  const MotionCommands::CarPosWithElbow* arg_1;
  MotionCommands::RETURN_ID_var result;
};

void _0RL_cd_7ac480c4252a17cd_b0000000::marshalArguments(cdrStream& _n)
{
  (const MotionCommands::CarPosWithElbow&) *arg_0 >>= _n;
  (const MotionCommands::CarPosWithElbow&) *arg_1 >>= _n;

}

void _0RL_cd_7ac480c4252a17cd_b0000000::unmarshalArguments(cdrStream& _n)
{
  (MotionCommands::CarPosWithElbow&)arg_0_ <<= _n;
  arg_0 = &arg_0_;
  (MotionCommands::CarPosWithElbow&)arg_1_ <<= _n;
  arg_1 = &arg_1_;

}

void _0RL_cd_7ac480c4252a17cd_b0000000::marshalReturnedValues(cdrStream& _n)
{
  (const MotionCommands::RETURN_ID&) result >>= _n;

}

void _0RL_cd_7ac480c4252a17cd_b0000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new MotionCommands::RETURN_ID;
  (MotionCommands::RETURN_ID&)result <<= _n;

}

const char* const _0RL_cd_7ac480c4252a17cd_b0000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_7ac480c4252a17cd_c0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_7ac480c4252a17cd_b0000000* tcd = (_0RL_cd_7ac480c4252a17cd_b0000000*)cd;
  _impl_MotionCommands* impl = (_impl_MotionCommands*) svnt->_ptrToInterface(MotionCommands::_PD_repoId);
  tcd->result = impl->moveLinearCartesianAbs(*tcd->arg_0, *tcd->arg_1);


}

MotionCommands::RETURN_ID* _objref_MotionCommands::moveLinearCartesianAbs(const ::MotionCommands::CarPosWithElbow& rArm, const ::MotionCommands::CarPosWithElbow& lArm)
{
  _0RL_cd_7ac480c4252a17cd_b0000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_c0000000, "moveLinearCartesianAbs", 23);
  _call_desc.arg_0 = &(::MotionCommands::CarPosWithElbow&) rArm;
  _call_desc.arg_1 = &(::MotionCommands::CarPosWithElbow&) lArm;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Local call call-back function.
static void
_0RL_lcfn_7ac480c4252a17cd_d0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_7ac480c4252a17cd_b0000000* tcd = (_0RL_cd_7ac480c4252a17cd_b0000000*)cd;
  _impl_MotionCommands* impl = (_impl_MotionCommands*) svnt->_ptrToInterface(MotionCommands::_PD_repoId);
  tcd->result = impl->moveLinearCartesianRel(*tcd->arg_0, *tcd->arg_1);


}

MotionCommands::RETURN_ID* _objref_MotionCommands::moveLinearCartesianRel(const ::MotionCommands::CarPosWithElbow& rArm, const ::MotionCommands::CarPosWithElbow& lArm)
{
  _0RL_cd_7ac480c4252a17cd_b0000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_d0000000, "moveLinearCartesianRel", 23);
  _call_desc.arg_0 = &(::MotionCommands::CarPosWithElbow&) rArm;
  _call_desc.arg_1 = &(::MotionCommands::CarPosWithElbow&) lArm;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Proxy call descriptor class. Mangled signature:
//  _cMotionCommands_mRETURN__ID_i_cMotionCommands_mJointPos
class _0RL_cd_7ac480c4252a17cd_e0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_7ac480c4252a17cd_e0000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  MotionCommands::JointPos_var arg_0_;
  const MotionCommands::JointPos* arg_0;
  MotionCommands::RETURN_ID_var result;
};

void _0RL_cd_7ac480c4252a17cd_e0000000::marshalArguments(cdrStream& _n)
{
  (const MotionCommands::JointPos&) *arg_0 >>= _n;

}

void _0RL_cd_7ac480c4252a17cd_e0000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = new MotionCommands::JointPos;
  (MotionCommands::JointPos&)arg_0_ <<= _n;
  arg_0 = &arg_0_.in();

}

void _0RL_cd_7ac480c4252a17cd_e0000000::marshalReturnedValues(cdrStream& _n)
{
  (const MotionCommands::RETURN_ID&) result >>= _n;

}

void _0RL_cd_7ac480c4252a17cd_e0000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new MotionCommands::RETURN_ID;
  (MotionCommands::RETURN_ID&)result <<= _n;

}

const char* const _0RL_cd_7ac480c4252a17cd_e0000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_7ac480c4252a17cd_f0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_7ac480c4252a17cd_e0000000* tcd = (_0RL_cd_7ac480c4252a17cd_e0000000*)cd;
  _impl_MotionCommands* impl = (_impl_MotionCommands*) svnt->_ptrToInterface(MotionCommands::_PD_repoId);
  tcd->result = impl->movePTPJointAbs(*tcd->arg_0);


}

MotionCommands::RETURN_ID* _objref_MotionCommands::movePTPJointAbs(const ::MotionCommands::JointPos& jointPoints)
{
  _0RL_cd_7ac480c4252a17cd_e0000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_f0000000, "movePTPJointAbs", 16);
  _call_desc.arg_0 = &(::MotionCommands::JointPos&) jointPoints;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Local call call-back function.
static void
_0RL_lcfn_7ac480c4252a17cd_01000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_7ac480c4252a17cd_e0000000* tcd = (_0RL_cd_7ac480c4252a17cd_e0000000*)cd;
  _impl_MotionCommands* impl = (_impl_MotionCommands*) svnt->_ptrToInterface(MotionCommands::_PD_repoId);
  tcd->result = impl->movePTPJointRel(*tcd->arg_0);


}

MotionCommands::RETURN_ID* _objref_MotionCommands::movePTPJointRel(const ::MotionCommands::JointPos& jointPoints)
{
  _0RL_cd_7ac480c4252a17cd_e0000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_01000000, "movePTPJointRel", 16);
  _call_desc.arg_0 = &(::MotionCommands::JointPos&) jointPoints;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Proxy call descriptor class. Mangled signature:
//  _cMotionCommands_mRETURN__ID_i_cMotionCommands_mJointPosSeq_i_cMotionCommands_mDoubleSeq
class _0RL_cd_7ac480c4252a17cd_11000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_7ac480c4252a17cd_11000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  MotionCommands::JointPosSeq_var arg_0_;
  const MotionCommands::JointPosSeq* arg_0;
  MotionCommands::DoubleSeq_var arg_1_;
  const MotionCommands::DoubleSeq* arg_1;
  MotionCommands::RETURN_ID_var result;
};

void _0RL_cd_7ac480c4252a17cd_11000000::marshalArguments(cdrStream& _n)
{
  (const MotionCommands::JointPosSeq&) *arg_0 >>= _n;
  (const MotionCommands::DoubleSeq&) *arg_1 >>= _n;

}

void _0RL_cd_7ac480c4252a17cd_11000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = new MotionCommands::JointPosSeq;
  (MotionCommands::JointPosSeq&)arg_0_ <<= _n;
  arg_0 = &arg_0_.in();
  arg_1_ = new MotionCommands::DoubleSeq;
  (MotionCommands::DoubleSeq&)arg_1_ <<= _n;
  arg_1 = &arg_1_.in();

}

void _0RL_cd_7ac480c4252a17cd_11000000::marshalReturnedValues(cdrStream& _n)
{
  (const MotionCommands::RETURN_ID&) result >>= _n;

}

void _0RL_cd_7ac480c4252a17cd_11000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new MotionCommands::RETURN_ID;
  (MotionCommands::RETURN_ID&)result <<= _n;

}

const char* const _0RL_cd_7ac480c4252a17cd_11000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_7ac480c4252a17cd_21000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_7ac480c4252a17cd_11000000* tcd = (_0RL_cd_7ac480c4252a17cd_11000000*)cd;
  _impl_MotionCommands* impl = (_impl_MotionCommands*) svnt->_ptrToInterface(MotionCommands::_PD_repoId);
  tcd->result = impl->movePTPJointAbsSeq(*tcd->arg_0, *tcd->arg_1);


}

MotionCommands::RETURN_ID* _objref_MotionCommands::movePTPJointAbsSeq(const ::MotionCommands::JointPosSeq& jointPointsSeq, const ::MotionCommands::DoubleSeq& timeSeq)
{
  _0RL_cd_7ac480c4252a17cd_11000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_21000000, "movePTPJointAbsSeq", 19);
  _call_desc.arg_0 = &(::MotionCommands::JointPosSeq&) jointPointsSeq;
  _call_desc.arg_1 = &(::MotionCommands::DoubleSeq&) timeSeq;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Local call call-back function.
static void
_0RL_lcfn_7ac480c4252a17cd_31000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_7ac480c4252a17cd_70000000* tcd = (_0RL_cd_7ac480c4252a17cd_70000000*)cd;
  _impl_MotionCommands* impl = (_impl_MotionCommands*) svnt->_ptrToInterface(MotionCommands::_PD_repoId);
  tcd->result = impl->openGripper();


}

MotionCommands::RETURN_ID* _objref_MotionCommands::openGripper()
{
  _0RL_cd_7ac480c4252a17cd_70000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_31000000, "openGripper", 12);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Proxy call descriptor class. Mangled signature:
//  _cMotionCommands_mRETURN__ID_i_cunsigned_plong
class _0RL_cd_7ac480c4252a17cd_41000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_7ac480c4252a17cd_41000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  MotionCommands::ULONG arg_0;
  MotionCommands::RETURN_ID_var result;
};

void _0RL_cd_7ac480c4252a17cd_41000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_7ac480c4252a17cd_41000000::unmarshalArguments(cdrStream& _n)
{
  (MotionCommands::ULONG&)arg_0 <<= _n;

}

void _0RL_cd_7ac480c4252a17cd_41000000::marshalReturnedValues(cdrStream& _n)
{
  (const MotionCommands::RETURN_ID&) result >>= _n;

}

void _0RL_cd_7ac480c4252a17cd_41000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new MotionCommands::RETURN_ID;
  (MotionCommands::RETURN_ID&)result <<= _n;

}

const char* const _0RL_cd_7ac480c4252a17cd_41000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_7ac480c4252a17cd_51000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_7ac480c4252a17cd_41000000* tcd = (_0RL_cd_7ac480c4252a17cd_41000000*)cd;
  _impl_MotionCommands* impl = (_impl_MotionCommands*) svnt->_ptrToInterface(MotionCommands::_PD_repoId);
  tcd->result = impl->setSpeedCartesian(tcd->arg_0);


}

MotionCommands::RETURN_ID* _objref_MotionCommands::setSpeedCartesian(::MotionCommands::ULONG spdRatio)
{
  _0RL_cd_7ac480c4252a17cd_41000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_51000000, "setSpeedCartesian", 18);
  _call_desc.arg_0 = spdRatio;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Local call call-back function.
static void
_0RL_lcfn_7ac480c4252a17cd_61000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_7ac480c4252a17cd_41000000* tcd = (_0RL_cd_7ac480c4252a17cd_41000000*)cd;
  _impl_MotionCommands* impl = (_impl_MotionCommands*) svnt->_ptrToInterface(MotionCommands::_PD_repoId);
  tcd->result = impl->setSpeedJoint(tcd->arg_0);


}

MotionCommands::RETURN_ID* _objref_MotionCommands::setSpeedJoint(::MotionCommands::ULONG spdRatio)
{
  _0RL_cd_7ac480c4252a17cd_41000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_61000000, "setSpeedJoint", 14);
  _call_desc.arg_0 = spdRatio;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Proxy call descriptor class. Mangled signature:
//  _cMotionCommands_mRETURN__ID_i_cdouble
class _0RL_cd_7ac480c4252a17cd_71000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_7ac480c4252a17cd_71000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Double arg_0;
  MotionCommands::RETURN_ID_var result;
};

void _0RL_cd_7ac480c4252a17cd_71000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_7ac480c4252a17cd_71000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Double&)arg_0 <<= _n;

}

void _0RL_cd_7ac480c4252a17cd_71000000::marshalReturnedValues(cdrStream& _n)
{
  (const MotionCommands::RETURN_ID&) result >>= _n;

}

void _0RL_cd_7ac480c4252a17cd_71000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new MotionCommands::RETURN_ID;
  (MotionCommands::RETURN_ID&)result <<= _n;

}

const char* const _0RL_cd_7ac480c4252a17cd_71000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_7ac480c4252a17cd_81000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_7ac480c4252a17cd_71000000* tcd = (_0RL_cd_7ac480c4252a17cd_71000000*)cd;
  _impl_MotionCommands* impl = (_impl_MotionCommands*) svnt->_ptrToInterface(MotionCommands::_PD_repoId);
  tcd->result = impl->setMotionTime(tcd->arg_0);


}

MotionCommands::RETURN_ID* _objref_MotionCommands::setMotionTime(::CORBA::Double motionTime)
{
  _0RL_cd_7ac480c4252a17cd_71000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_81000000, "setMotionTime", 14);
  _call_desc.arg_0 = motionTime;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}
_pof_MotionCommands::~_pof_MotionCommands() {}


omniObjRef*
_pof_MotionCommands::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::_objref_MotionCommands(ior, id);
}


::CORBA::Boolean
_pof_MotionCommands::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::MotionCommands::_PD_repoId) )
    return 1;
  
  return 0;
}

const _pof_MotionCommands _the_pof_MotionCommands;

_impl_MotionCommands::~_impl_MotionCommands() {}


::CORBA::Boolean
_impl_MotionCommands::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "closeGripper") ) {

    _0RL_cd_7ac480c4252a17cd_70000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_80000000, "closeGripper", 13, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "moveGripper") ) {

    _0RL_cd_7ac480c4252a17cd_90000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_a0000000, "moveGripper", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "moveLinearCartesianAbs") ) {

    _0RL_cd_7ac480c4252a17cd_b0000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_c0000000, "moveLinearCartesianAbs", 23, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "moveLinearCartesianRel") ) {

    _0RL_cd_7ac480c4252a17cd_b0000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_d0000000, "moveLinearCartesianRel", 23, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "movePTPJointAbs") ) {

    _0RL_cd_7ac480c4252a17cd_e0000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_f0000000, "movePTPJointAbs", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "movePTPJointRel") ) {

    _0RL_cd_7ac480c4252a17cd_e0000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_01000000, "movePTPJointRel", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "movePTPJointAbsSeq") ) {

    _0RL_cd_7ac480c4252a17cd_11000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_21000000, "movePTPJointAbsSeq", 19, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "openGripper") ) {

    _0RL_cd_7ac480c4252a17cd_70000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_31000000, "openGripper", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setSpeedCartesian") ) {

    _0RL_cd_7ac480c4252a17cd_41000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_51000000, "setSpeedCartesian", 18, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setSpeedJoint") ) {

    _0RL_cd_7ac480c4252a17cd_41000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_61000000, "setSpeedJoint", 14, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setMotionTime") ) {

    _0RL_cd_7ac480c4252a17cd_71000000 _call_desc(_0RL_lcfn_7ac480c4252a17cd_81000000, "setMotionTime", 14, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
_impl_MotionCommands::_ptrToInterface(const char* id)
{
  if( id == ::MotionCommands::_PD_repoId )
    return (::_impl_MotionCommands*) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::MotionCommands::_PD_repoId) )
    return (::_impl_MotionCommands*) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
_impl_MotionCommands::_mostDerivedRepoId()
{
  return ::MotionCommands::_PD_repoId;
}

POA_CommonCommands::~POA_CommonCommands() {}

POA_MotionCommands::~POA_MotionCommands() {}

