// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "ManipulatorCommonInterface_DataTypes.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



void
RTC::LimitValue::operator>>= (cdrStream &_n) const
{
  upper >>= _n;
  lower >>= _n;

}

void
RTC::LimitValue::operator<<= (cdrStream &_n)
{
  (::CORBA::Double&)upper <<= _n;
  (::CORBA::Double&)lower <<= _n;

}

void
RTC::RETURN_ID::operator>>= (cdrStream &_n) const
{
  id >>= _n;
  _n.marshalString(comment,0);

}

void
RTC::RETURN_ID::operator<<= (cdrStream &_n)
{
  (::CORBA::Long&)id <<= _n;
  comment = _n.unmarshalString(0);

}

void
RTC::TimedJointPos::operator>>= (cdrStream &_n) const
{
  (const Time&) tm >>= _n;
  (const JointPos&) pos >>= _n;

}

void
RTC::TimedJointPos::operator<<= (cdrStream &_n)
{
  (Time&)tm <<= _n;
  (JointPos&)pos <<= _n;

}

