// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "ManipulatorCommonInterface_Common.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



void
RTC::Alarm::operator>>= (cdrStream &_n) const
{
  code >>= _n;
  type >>= _n;
  _n.marshalString(description,0);

}

void
RTC::Alarm::operator<<= (cdrStream &_n)
{
  (::CORBA::ULong&)code <<= _n;
  (AlarmType&)type <<= _n;
  description = _n.unmarshalString(0);

}

void
RTC::ManipInfo::operator>>= (cdrStream &_n) const
{
  _n.marshalString(manufactur,0);
  _n.marshalString(type,0);
  axisNum >>= _n;
  cmdCycle >>= _n;
  _n.marshalBoolean(isGripper);

}

void
RTC::ManipInfo::operator<<= (cdrStream &_n)
{
  manufactur = _n.unmarshalString(0);
  type = _n.unmarshalString(0);
  (ULONG&)axisNum <<= _n;
  (ULONG&)cmdCycle <<= _n;
  isGripper = _n.unmarshalBoolean();

}

_init_in_def_( const ::CORBA::ULong RTC::CONST_BINARY_00000001 = 1U; )

_init_in_def_( const ::CORBA::ULong RTC::CONST_BINARY_00000010 = 2U; )

_init_in_def_( const ::CORBA::ULong RTC::CONST_BINARY_00000100 = 4U; )

_init_in_def_( const ::CORBA::ULong RTC::CONST_BINARY_00001000 = 8U; )

ManipulatorCommonInterface_Common_ptr ManipulatorCommonInterface_Common_Helper::_nil() {
  return ::ManipulatorCommonInterface_Common::_nil();
}

::CORBA::Boolean ManipulatorCommonInterface_Common_Helper::is_nil(::ManipulatorCommonInterface_Common_ptr p) {
  return ::CORBA::is_nil(p);

}

void ManipulatorCommonInterface_Common_Helper::release(::ManipulatorCommonInterface_Common_ptr p) {
  ::CORBA::release(p);
}

void ManipulatorCommonInterface_Common_Helper::marshalObjRef(::ManipulatorCommonInterface_Common_ptr obj, cdrStream& s) {
  ::ManipulatorCommonInterface_Common::_marshalObjRef(obj, s);
}

ManipulatorCommonInterface_Common_ptr ManipulatorCommonInterface_Common_Helper::unmarshalObjRef(cdrStream& s) {
  return ::ManipulatorCommonInterface_Common::_unmarshalObjRef(s);
}

void ManipulatorCommonInterface_Common_Helper::duplicate(::ManipulatorCommonInterface_Common_ptr obj) {
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
}

ManipulatorCommonInterface_Common_ptr
ManipulatorCommonInterface_Common::_duplicate(::ManipulatorCommonInterface_Common_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
  return obj;
}

ManipulatorCommonInterface_Common_ptr
ManipulatorCommonInterface_Common::_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


ManipulatorCommonInterface_Common_ptr
ManipulatorCommonInterface_Common::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

ManipulatorCommonInterface_Common_ptr
ManipulatorCommonInterface_Common::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_ManipulatorCommonInterface_Common _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_ManipulatorCommonInterface_Common* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_ManipulatorCommonInterface_Common;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* ManipulatorCommonInterface_Common::_PD_repoId = "IDL:ManipulatorCommonInterface_Common:1.0";


_objref_ManipulatorCommonInterface_Common::~_objref_ManipulatorCommonInterface_Common() {
  
}


_objref_ManipulatorCommonInterface_Common::_objref_ManipulatorCommonInterface_Common(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::ManipulatorCommonInterface_Common::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
_objref_ManipulatorCommonInterface_Common::_ptrToObjRef(const char* id)
{
  if( id == ::ManipulatorCommonInterface_Common::_PD_repoId )
    return (::ManipulatorCommonInterface_Common_ptr) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::ManipulatorCommonInterface_Common::_PD_repoId) )
    return (::ManipulatorCommonInterface_Common_ptr) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Proxy call descriptor class. Mangled signature:
//  _cRTC_mRETURN__ID
class _0RL_cd_5adb1cd235965950_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_5adb1cd235965950_00000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  RTC::RETURN_ID_var result;
};

void _0RL_cd_5adb1cd235965950_00000000::marshalReturnedValues(cdrStream& _n)
{
  (const RTC::RETURN_ID&) result >>= _n;

}

void _0RL_cd_5adb1cd235965950_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new RTC::RETURN_ID;
  (RTC::RETURN_ID&)result <<= _n;

}

const char* const _0RL_cd_5adb1cd235965950_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_5adb1cd235965950_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_5adb1cd235965950_00000000* tcd = (_0RL_cd_5adb1cd235965950_00000000*)cd;
  _impl_ManipulatorCommonInterface_Common* impl = (_impl_ManipulatorCommonInterface_Common*) svnt->_ptrToInterface(ManipulatorCommonInterface_Common::_PD_repoId);
  tcd->result = impl->clearAlarms();


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Common::clearAlarms()
{
  _0RL_cd_5adb1cd235965950_00000000 _call_desc(_0RL_lcfn_5adb1cd235965950_10000000, "clearAlarms", 12);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Proxy call descriptor class. Mangled signature:
//  _cRTC_mRETURN__ID_o_cRTC_mAlarmSeq
class _0RL_cd_5adb1cd235965950_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_5adb1cd235965950_20000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  RTC::AlarmSeq_var arg_0;
  RTC::RETURN_ID_var result;
};

void _0RL_cd_5adb1cd235965950_20000000::marshalReturnedValues(cdrStream& _n)
{
  (const RTC::RETURN_ID&) result >>= _n;
  (const RTC::AlarmSeq&) arg_0 >>= _n;

}

void _0RL_cd_5adb1cd235965950_20000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new RTC::RETURN_ID;
  (RTC::RETURN_ID&)result <<= _n;
  arg_0 = new RTC::AlarmSeq;
  (RTC::AlarmSeq&)arg_0 <<= _n;

}

const char* const _0RL_cd_5adb1cd235965950_20000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_5adb1cd235965950_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_5adb1cd235965950_20000000* tcd = (_0RL_cd_5adb1cd235965950_20000000*)cd;
  _impl_ManipulatorCommonInterface_Common* impl = (_impl_ManipulatorCommonInterface_Common*) svnt->_ptrToInterface(ManipulatorCommonInterface_Common::_PD_repoId);
  tcd->result = impl->getActiveAlarm(tcd->arg_0.out());


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Common::getActiveAlarm(::RTC::AlarmSeq_out alarms)
{
  _0RL_cd_5adb1cd235965950_20000000 _call_desc(_0RL_lcfn_5adb1cd235965950_30000000, "getActiveAlarm", 15);


  _invoke(_call_desc);
  alarms = _call_desc.arg_0._retn();
  return _call_desc.result._retn();


}
// Proxy call descriptor class. Mangled signature:
//  _cRTC_mRETURN__ID_o_cRTC_mJointPos
class _0RL_cd_5adb1cd235965950_40000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_5adb1cd235965950_40000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  RTC::JointPos_var arg_0;
  RTC::RETURN_ID_var result;
};

void _0RL_cd_5adb1cd235965950_40000000::marshalReturnedValues(cdrStream& _n)
{
  (const RTC::RETURN_ID&) result >>= _n;
  (const RTC::JointPos&) arg_0 >>= _n;

}

void _0RL_cd_5adb1cd235965950_40000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new RTC::RETURN_ID;
  (RTC::RETURN_ID&)result <<= _n;
  arg_0 = new RTC::JointPos;
  (RTC::JointPos&)arg_0 <<= _n;

}

const char* const _0RL_cd_5adb1cd235965950_40000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_5adb1cd235965950_50000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_5adb1cd235965950_40000000* tcd = (_0RL_cd_5adb1cd235965950_40000000*)cd;
  _impl_ManipulatorCommonInterface_Common* impl = (_impl_ManipulatorCommonInterface_Common*) svnt->_ptrToInterface(ManipulatorCommonInterface_Common::_PD_repoId);
  tcd->result = impl->getFeedbackPosJoint(tcd->arg_0.out());


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Common::getFeedbackPosJoint(::RTC::JointPos_out pos)
{
  _0RL_cd_5adb1cd235965950_40000000 _call_desc(_0RL_lcfn_5adb1cd235965950_50000000, "getFeedbackPosJoint", 20);


  _invoke(_call_desc);
  pos = _call_desc.arg_0._retn();
  return _call_desc.result._retn();


}
// Proxy call descriptor class. Mangled signature:
//  _cRTC_mRETURN__ID_o_cRTC_mManipInfo
class _0RL_cd_5adb1cd235965950_60000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_5adb1cd235965950_60000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  RTC::ManipInfo_var arg_0;
  RTC::RETURN_ID_var result;
};

void _0RL_cd_5adb1cd235965950_60000000::marshalReturnedValues(cdrStream& _n)
{
  (const RTC::RETURN_ID&) result >>= _n;
  (const RTC::ManipInfo&) arg_0 >>= _n;

}

void _0RL_cd_5adb1cd235965950_60000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new RTC::RETURN_ID;
  (RTC::RETURN_ID&)result <<= _n;
  arg_0 = new RTC::ManipInfo;
  (RTC::ManipInfo&)arg_0 <<= _n;

}

const char* const _0RL_cd_5adb1cd235965950_60000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_5adb1cd235965950_70000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_5adb1cd235965950_60000000* tcd = (_0RL_cd_5adb1cd235965950_60000000*)cd;
  _impl_ManipulatorCommonInterface_Common* impl = (_impl_ManipulatorCommonInterface_Common*) svnt->_ptrToInterface(ManipulatorCommonInterface_Common::_PD_repoId);
  tcd->result = impl->getManipInfo(tcd->arg_0.out());


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Common::getManipInfo(::RTC::ManipInfo_out manipInfo)
{
  _0RL_cd_5adb1cd235965950_60000000 _call_desc(_0RL_lcfn_5adb1cd235965950_70000000, "getManipInfo", 13);


  _invoke(_call_desc);
  manipInfo = _call_desc.arg_0._retn();
  return _call_desc.result._retn();


}
// Proxy call descriptor class. Mangled signature:
//  _cRTC_mRETURN__ID_o_cRTC_mLimitSeq
class _0RL_cd_5adb1cd235965950_80000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_5adb1cd235965950_80000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  RTC::LimitSeq_var arg_0;
  RTC::RETURN_ID_var result;
};

void _0RL_cd_5adb1cd235965950_80000000::marshalReturnedValues(cdrStream& _n)
{
  (const RTC::RETURN_ID&) result >>= _n;
  (const RTC::LimitSeq&) arg_0 >>= _n;

}

void _0RL_cd_5adb1cd235965950_80000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new RTC::RETURN_ID;
  (RTC::RETURN_ID&)result <<= _n;
  arg_0 = new RTC::LimitSeq;
  (RTC::LimitSeq&)arg_0 <<= _n;

}

const char* const _0RL_cd_5adb1cd235965950_80000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_5adb1cd235965950_90000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_5adb1cd235965950_80000000* tcd = (_0RL_cd_5adb1cd235965950_80000000*)cd;
  _impl_ManipulatorCommonInterface_Common* impl = (_impl_ManipulatorCommonInterface_Common*) svnt->_ptrToInterface(ManipulatorCommonInterface_Common::_PD_repoId);
  tcd->result = impl->getSoftLimitJoint(tcd->arg_0.out());


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Common::getSoftLimitJoint(::RTC::LimitSeq_out softLimit)
{
  _0RL_cd_5adb1cd235965950_80000000 _call_desc(_0RL_lcfn_5adb1cd235965950_90000000, "getSoftLimitJoint", 18);


  _invoke(_call_desc);
  softLimit = _call_desc.arg_0._retn();
  return _call_desc.result._retn();


}
// Proxy call descriptor class. Mangled signature:
//  _cRTC_mRETURN__ID_o_cunsigned_plong
class _0RL_cd_5adb1cd235965950_a0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_5adb1cd235965950_a0000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  RTC::ULONG arg_0;
  RTC::RETURN_ID_var result;
};

void _0RL_cd_5adb1cd235965950_a0000000::marshalReturnedValues(cdrStream& _n)
{
  (const RTC::RETURN_ID&) result >>= _n;
  arg_0 >>= _n;

}

void _0RL_cd_5adb1cd235965950_a0000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new RTC::RETURN_ID;
  (RTC::RETURN_ID&)result <<= _n;
  (RTC::ULONG&)arg_0 <<= _n;

}

const char* const _0RL_cd_5adb1cd235965950_a0000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_5adb1cd235965950_b0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_5adb1cd235965950_a0000000* tcd = (_0RL_cd_5adb1cd235965950_a0000000*)cd;
  _impl_ManipulatorCommonInterface_Common* impl = (_impl_ManipulatorCommonInterface_Common*) svnt->_ptrToInterface(ManipulatorCommonInterface_Common::_PD_repoId);
  tcd->result = impl->getState(tcd->arg_0);


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Common::getState(::RTC::ULONG& state)
{
  _0RL_cd_5adb1cd235965950_a0000000 _call_desc(_0RL_lcfn_5adb1cd235965950_b0000000, "getState", 9);


  _invoke(_call_desc);
  state = _call_desc.arg_0;
  return _call_desc.result._retn();


}
// Local call call-back function.
static void
_0RL_lcfn_5adb1cd235965950_c0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_5adb1cd235965950_00000000* tcd = (_0RL_cd_5adb1cd235965950_00000000*)cd;
  _impl_ManipulatorCommonInterface_Common* impl = (_impl_ManipulatorCommonInterface_Common*) svnt->_ptrToInterface(ManipulatorCommonInterface_Common::_PD_repoId);
  tcd->result = impl->servoOFF();


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Common::servoOFF()
{
  _0RL_cd_5adb1cd235965950_00000000 _call_desc(_0RL_lcfn_5adb1cd235965950_c0000000, "servoOFF", 9);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Local call call-back function.
static void
_0RL_lcfn_5adb1cd235965950_d0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_5adb1cd235965950_00000000* tcd = (_0RL_cd_5adb1cd235965950_00000000*)cd;
  _impl_ManipulatorCommonInterface_Common* impl = (_impl_ManipulatorCommonInterface_Common*) svnt->_ptrToInterface(ManipulatorCommonInterface_Common::_PD_repoId);
  tcd->result = impl->servoON();


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Common::servoON()
{
  _0RL_cd_5adb1cd235965950_00000000 _call_desc(_0RL_lcfn_5adb1cd235965950_d0000000, "servoON", 8);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}
// Proxy call descriptor class. Mangled signature:
//  _cRTC_mRETURN__ID_i_cRTC_mLimitSeq
class _0RL_cd_5adb1cd235965950_e0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_5adb1cd235965950_e0000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  RTC::LimitSeq_var arg_0_;
  const RTC::LimitSeq* arg_0;
  RTC::RETURN_ID_var result;
};

void _0RL_cd_5adb1cd235965950_e0000000::marshalArguments(cdrStream& _n)
{
  (const RTC::LimitSeq&) *arg_0 >>= _n;

}

void _0RL_cd_5adb1cd235965950_e0000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = new RTC::LimitSeq;
  (RTC::LimitSeq&)arg_0_ <<= _n;
  arg_0 = &arg_0_.in();

}

void _0RL_cd_5adb1cd235965950_e0000000::marshalReturnedValues(cdrStream& _n)
{
  (const RTC::RETURN_ID&) result >>= _n;

}

void _0RL_cd_5adb1cd235965950_e0000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new RTC::RETURN_ID;
  (RTC::RETURN_ID&)result <<= _n;

}

const char* const _0RL_cd_5adb1cd235965950_e0000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_5adb1cd235965950_f0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_5adb1cd235965950_e0000000* tcd = (_0RL_cd_5adb1cd235965950_e0000000*)cd;
  _impl_ManipulatorCommonInterface_Common* impl = (_impl_ManipulatorCommonInterface_Common*) svnt->_ptrToInterface(ManipulatorCommonInterface_Common::_PD_repoId);
  tcd->result = impl->setSoftLimitJoint(*tcd->arg_0);


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Common::setSoftLimitJoint(const ::RTC::LimitSeq& softLimit)
{
  _0RL_cd_5adb1cd235965950_e0000000 _call_desc(_0RL_lcfn_5adb1cd235965950_f0000000, "setSoftLimitJoint", 18);
  _call_desc.arg_0 = &(::RTC::LimitSeq&) softLimit;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}
_pof_ManipulatorCommonInterface_Common::~_pof_ManipulatorCommonInterface_Common() {}


omniObjRef*
_pof_ManipulatorCommonInterface_Common::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::_objref_ManipulatorCommonInterface_Common(ior, id);
}


::CORBA::Boolean
_pof_ManipulatorCommonInterface_Common::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::ManipulatorCommonInterface_Common::_PD_repoId) )
    return 1;
  
  return 0;
}

const _pof_ManipulatorCommonInterface_Common _the_pof_ManipulatorCommonInterface__Common;

_impl_ManipulatorCommonInterface_Common::~_impl_ManipulatorCommonInterface_Common() {}


::CORBA::Boolean
_impl_ManipulatorCommonInterface_Common::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "clearAlarms") ) {

    _0RL_cd_5adb1cd235965950_00000000 _call_desc(_0RL_lcfn_5adb1cd235965950_10000000, "clearAlarms", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getActiveAlarm") ) {

    _0RL_cd_5adb1cd235965950_20000000 _call_desc(_0RL_lcfn_5adb1cd235965950_30000000, "getActiveAlarm", 15, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getFeedbackPosJoint") ) {

    _0RL_cd_5adb1cd235965950_40000000 _call_desc(_0RL_lcfn_5adb1cd235965950_50000000, "getFeedbackPosJoint", 20, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getManipInfo") ) {

    _0RL_cd_5adb1cd235965950_60000000 _call_desc(_0RL_lcfn_5adb1cd235965950_70000000, "getManipInfo", 13, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getSoftLimitJoint") ) {

    _0RL_cd_5adb1cd235965950_80000000 _call_desc(_0RL_lcfn_5adb1cd235965950_90000000, "getSoftLimitJoint", 18, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "getState") ) {

    _0RL_cd_5adb1cd235965950_a0000000 _call_desc(_0RL_lcfn_5adb1cd235965950_b0000000, "getState", 9, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "servoOFF") ) {

    _0RL_cd_5adb1cd235965950_00000000 _call_desc(_0RL_lcfn_5adb1cd235965950_c0000000, "servoOFF", 9, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "servoON") ) {

    _0RL_cd_5adb1cd235965950_00000000 _call_desc(_0RL_lcfn_5adb1cd235965950_d0000000, "servoON", 8, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "setSoftLimitJoint") ) {

    _0RL_cd_5adb1cd235965950_e0000000 _call_desc(_0RL_lcfn_5adb1cd235965950_f0000000, "setSoftLimitJoint", 18, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
_impl_ManipulatorCommonInterface_Common::_ptrToInterface(const char* id)
{
  if( id == ::ManipulatorCommonInterface_Common::_PD_repoId )
    return (::_impl_ManipulatorCommonInterface_Common*) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::ManipulatorCommonInterface_Common::_PD_repoId) )
    return (::_impl_ManipulatorCommonInterface_Common*) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
_impl_ManipulatorCommonInterface_Common::_mostDerivedRepoId()
{
  return ::ManipulatorCommonInterface_Common::_PD_repoId;
}

POA_ManipulatorCommonInterface_Common::~POA_ManipulatorCommonInterface_Common() {}

