// This file is generated by omniidl (C++ backend) - omniORB_4_1. Do not edit.

#include "RecognitionServiceExt.hh"

OMNI_USING_NAMESPACE(omni)

static const char* _0RL_dyn_library_version = omniORB_4_1_dyn;

static ::CORBA::TypeCode::_Tracker _0RL_tcTrack(__FILE__);

static CORBA::TypeCode_ptr _0RL_tc_RecognitionServiceExt_mDblSeq = CORBA::TypeCode::PR_alias_tc("IDL:RecognitionServiceExt/DblSeq:1.0", "DblSeq", CORBA::TypeCode::PR_sequence_tc(0, CORBA::TypeCode::PR_double_tc(), &_0RL_tcTrack), &_0RL_tcTrack);


const CORBA::TypeCode_ptr RecognitionServiceExt::_tc_DblSeq = _0RL_tc_RecognitionServiceExt_mDblSeq;

const CORBA::TypeCode_ptr _tc_RecognitionServiceExt = CORBA::TypeCode::PR_interface_tc("IDL:RecognitionServiceExt:1.0", "RecognitionServiceExt", &_0RL_tcTrack);

static CORBA::TypeCode_ptr _0RL_tc_RecognitionResultServiceExt_mDblSeqResult = CORBA::TypeCode::PR_alias_tc("IDL:RecognitionResultServiceExt/DblSeqResult:1.0", "DblSeqResult", CORBA::TypeCode::PR_sequence_tc(0, CORBA::TypeCode::PR_double_tc(), &_0RL_tcTrack), &_0RL_tcTrack);


const CORBA::TypeCode_ptr RecognitionResultServiceExt::_tc_DblSeqResult = _0RL_tc_RecognitionResultServiceExt_mDblSeqResult;

const CORBA::TypeCode_ptr _tc_RecognitionResultServiceExt = CORBA::TypeCode::PR_interface_tc("IDL:RecognitionResultServiceExt:1.0", "RecognitionResultServiceExt", &_0RL_tcTrack);

static void _0RL_RecognitionServiceExt_mDblSeq_marshal_fn(cdrStream& _s, void* _v)
{
  RecognitionServiceExt::DblSeq* _p = (RecognitionServiceExt::DblSeq*)_v;
  *_p >>= _s;
}
static void _0RL_RecognitionServiceExt_mDblSeq_unmarshal_fn(cdrStream& _s, void*& _v)
{
  RecognitionServiceExt::DblSeq* _p = new RecognitionServiceExt::DblSeq;
  *_p <<= _s;
  _v = _p;
}
static void _0RL_RecognitionServiceExt_mDblSeq_destructor_fn(void* _v)
{
  RecognitionServiceExt::DblSeq* _p = (RecognitionServiceExt::DblSeq*)_v;
  delete _p;
}

void operator<<=(::CORBA::Any& _a, const RecognitionServiceExt::DblSeq& _s)
{
  RecognitionServiceExt::DblSeq* _p = new RecognitionServiceExt::DblSeq(_s);
  _a.PR_insert(_0RL_tc_RecognitionServiceExt_mDblSeq,
               _0RL_RecognitionServiceExt_mDblSeq_marshal_fn,
               _0RL_RecognitionServiceExt_mDblSeq_destructor_fn,
               _p);
}
void operator<<=(::CORBA::Any& _a, RecognitionServiceExt::DblSeq* _sp)
{
  _a.PR_insert(_0RL_tc_RecognitionServiceExt_mDblSeq,
               _0RL_RecognitionServiceExt_mDblSeq_marshal_fn,
               _0RL_RecognitionServiceExt_mDblSeq_destructor_fn,
               _sp);
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, RecognitionServiceExt::DblSeq*& _sp)
{
  return _a >>= (const RecognitionServiceExt::DblSeq*&) _sp;
}
::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, const RecognitionServiceExt::DblSeq*& _sp)
{
  void* _v;
  if (_a.PR_extract(_0RL_tc_RecognitionServiceExt_mDblSeq,
                    _0RL_RecognitionServiceExt_mDblSeq_unmarshal_fn,
                    _0RL_RecognitionServiceExt_mDblSeq_marshal_fn,
                    _0RL_RecognitionServiceExt_mDblSeq_destructor_fn,
                    _v)) {
    _sp = (const RecognitionServiceExt::DblSeq*)_v;
    return 1;
  }
  return 0;
}

static void _0RL_RecognitionServiceExt_marshal_fn(cdrStream& _s, void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  omniObjRef::_marshal(_o, _s);
}
static void _0RL_RecognitionServiceExt_unmarshal_fn(cdrStream& _s, void*& _v)
{
  omniObjRef* _o = omniObjRef::_unMarshal(RecognitionServiceExt::_PD_repoId, _s);
  _v = _o;
}
static void _0RL_RecognitionServiceExt_destructor_fn(void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  if (_o)
    omni::releaseObjRef(_o);
}

void operator<<=(::CORBA::Any& _a, RecognitionServiceExt_ptr _o)
{
  RecognitionServiceExt_ptr _no = RecognitionServiceExt::_duplicate(_o);
  _a.PR_insert(_tc_RecognitionServiceExt,
               _0RL_RecognitionServiceExt_marshal_fn,
               _0RL_RecognitionServiceExt_destructor_fn,
               _no->_PR_getobj());
}
void operator<<=(::CORBA::Any& _a, RecognitionServiceExt_ptr* _op)
{
  _a.PR_insert(_tc_RecognitionServiceExt,
               _0RL_RecognitionServiceExt_marshal_fn,
               _0RL_RecognitionServiceExt_destructor_fn,
               (*_op)->_PR_getobj());
  *_op = RecognitionServiceExt::_nil();
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, RecognitionServiceExt_ptr& _o)
{
  void* _v;
  if (_a.PR_extract(_tc_RecognitionServiceExt,
                    _0RL_RecognitionServiceExt_unmarshal_fn,
                    _0RL_RecognitionServiceExt_marshal_fn,
                    _0RL_RecognitionServiceExt_destructor_fn,
                    _v)) {
    omniObjRef* _r = (omniObjRef*)_v;
    if (_r)
      _o = (RecognitionServiceExt_ptr)_r->_ptrToObjRef(RecognitionServiceExt::_PD_repoId);
    else
      _o = RecognitionServiceExt::_nil();
    return 1;
  }
  return 0;
}

static void _0RL_RecognitionResultServiceExt_mDblSeqResult_marshal_fn(cdrStream& _s, void* _v)
{
  RecognitionResultServiceExt::DblSeqResult* _p = (RecognitionResultServiceExt::DblSeqResult*)_v;
  *_p >>= _s;
}
static void _0RL_RecognitionResultServiceExt_mDblSeqResult_unmarshal_fn(cdrStream& _s, void*& _v)
{
  RecognitionResultServiceExt::DblSeqResult* _p = new RecognitionResultServiceExt::DblSeqResult;
  *_p <<= _s;
  _v = _p;
}
static void _0RL_RecognitionResultServiceExt_mDblSeqResult_destructor_fn(void* _v)
{
  RecognitionResultServiceExt::DblSeqResult* _p = (RecognitionResultServiceExt::DblSeqResult*)_v;
  delete _p;
}

void operator<<=(::CORBA::Any& _a, const RecognitionResultServiceExt::DblSeqResult& _s)
{
  RecognitionResultServiceExt::DblSeqResult* _p = new RecognitionResultServiceExt::DblSeqResult(_s);
  _a.PR_insert(_0RL_tc_RecognitionResultServiceExt_mDblSeqResult,
               _0RL_RecognitionResultServiceExt_mDblSeqResult_marshal_fn,
               _0RL_RecognitionResultServiceExt_mDblSeqResult_destructor_fn,
               _p);
}
void operator<<=(::CORBA::Any& _a, RecognitionResultServiceExt::DblSeqResult* _sp)
{
  _a.PR_insert(_0RL_tc_RecognitionResultServiceExt_mDblSeqResult,
               _0RL_RecognitionResultServiceExt_mDblSeqResult_marshal_fn,
               _0RL_RecognitionResultServiceExt_mDblSeqResult_destructor_fn,
               _sp);
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, RecognitionResultServiceExt::DblSeqResult*& _sp)
{
  return _a >>= (const RecognitionResultServiceExt::DblSeqResult*&) _sp;
}
::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, const RecognitionResultServiceExt::DblSeqResult*& _sp)
{
  void* _v;
  if (_a.PR_extract(_0RL_tc_RecognitionResultServiceExt_mDblSeqResult,
                    _0RL_RecognitionResultServiceExt_mDblSeqResult_unmarshal_fn,
                    _0RL_RecognitionResultServiceExt_mDblSeqResult_marshal_fn,
                    _0RL_RecognitionResultServiceExt_mDblSeqResult_destructor_fn,
                    _v)) {
    _sp = (const RecognitionResultServiceExt::DblSeqResult*)_v;
    return 1;
  }
  return 0;
}

static void _0RL_RecognitionResultServiceExt_marshal_fn(cdrStream& _s, void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  omniObjRef::_marshal(_o, _s);
}
static void _0RL_RecognitionResultServiceExt_unmarshal_fn(cdrStream& _s, void*& _v)
{
  omniObjRef* _o = omniObjRef::_unMarshal(RecognitionResultServiceExt::_PD_repoId, _s);
  _v = _o;
}
static void _0RL_RecognitionResultServiceExt_destructor_fn(void* _v)
{
  omniObjRef* _o = (omniObjRef*)_v;
  if (_o)
    omni::releaseObjRef(_o);
}

void operator<<=(::CORBA::Any& _a, RecognitionResultServiceExt_ptr _o)
{
  RecognitionResultServiceExt_ptr _no = RecognitionResultServiceExt::_duplicate(_o);
  _a.PR_insert(_tc_RecognitionResultServiceExt,
               _0RL_RecognitionResultServiceExt_marshal_fn,
               _0RL_RecognitionResultServiceExt_destructor_fn,
               _no->_PR_getobj());
}
void operator<<=(::CORBA::Any& _a, RecognitionResultServiceExt_ptr* _op)
{
  _a.PR_insert(_tc_RecognitionResultServiceExt,
               _0RL_RecognitionResultServiceExt_marshal_fn,
               _0RL_RecognitionResultServiceExt_destructor_fn,
               (*_op)->_PR_getobj());
  *_op = RecognitionResultServiceExt::_nil();
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, RecognitionResultServiceExt_ptr& _o)
{
  void* _v;
  if (_a.PR_extract(_tc_RecognitionResultServiceExt,
                    _0RL_RecognitionResultServiceExt_unmarshal_fn,
                    _0RL_RecognitionResultServiceExt_marshal_fn,
                    _0RL_RecognitionResultServiceExt_destructor_fn,
                    _v)) {
    omniObjRef* _r = (omniObjRef*)_v;
    if (_r)
      _o = (RecognitionResultServiceExt_ptr)_r->_ptrToObjRef(RecognitionResultServiceExt::_PD_repoId);
    else
      _o = RecognitionResultServiceExt::_nil();
    return 1;
  }
  return 0;
}

