# DO NOT EDIT THIS FILE!
#
# Python module RTC__POA generated by omniidl

import omniORB
omniORB.updateModule("RTC__POA")

# ** 1. Stub files contributing to this module
import ManipulatorCommonInterface_Common_idl
import ManipulatorCommonInterface_MiddleLevel_idl
import ManipulatorCommonInterface_DataTypes_idl

# ** 2. Sub-modules

# ** 3. End
