/*
 * HIROControllerRtc.cpp
 *
 *  Created on: 2011-10-05
 *  Auto Generated by: gp.rb
 */

#include "ArmControllerRtc.h"

using namespace grasp;
using namespace std;
using namespace cnoid;

ArmControllerRtc* ArmControllerRtc::instance()
{
	static ArmControllerRtc* instance = new ArmControllerRtc();
	return instance;
}

int ArmControllerRtc::RtcStart()
{
	int argc= 1;
	char *argv[] = { (char *)("ArmControllerComp") };

	RTC::Manager* manager;
	manager = RTC::Manager::init(argc, argv);

	// Initialize manager
	manager->init(argc, argv);

	// Set module initialization proceduer
	// This procedure will be invoked in activateManager() function.
	manager->setModuleInitProc(MyModuleInit);

	// Activate manager and register to naming service
	manager->activateManager();

	// run the manager in blocking mode
	// runManager(false) is the default.
	//  manager->runManager();

	// If you want to run the manager in non-blocking mode, do like this
	manager->runManager(true);

	return 0;
}

void ArmControllerRtc::MyModuleInit(RTC::Manager* manager)
{
	ArmControllerInit(manager);

	// Create a component
	instance()->comp_ = (ArmController *)manager->createComponent("ArmController");
	if (instance()->comp_ ==NULL) {
		std::cerr << "Component create failed." << std::endl;
		abort();
	}

	return;
}
