// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __HiroNX_hh__
#define __HiroNX_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_HiroNX
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_HiroNX
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_HiroNX
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



#ifndef __HiroNX__
#define __HiroNX__
class HiroNX;
class _objref_HiroNX;
class _impl_HiroNX;

typedef _objref_HiroNX* HiroNX_ptr;
typedef HiroNX_ptr HiroNXRef;

class HiroNX_Helper {
public:
  typedef HiroNX_ptr _ptr_type;

  static _ptr_type _nil();
  static _CORBA_Boolean is_nil(_ptr_type);
  static void release(_ptr_type);
  static void duplicate(_ptr_type);
  static void marshalObjRef(_ptr_type, cdrStream&);
  static _ptr_type unmarshalObjRef(cdrStream&);
};

typedef _CORBA_ObjRef_Var<_objref_HiroNX, HiroNX_Helper> HiroNX_var;
typedef _CORBA_ObjRef_OUT_arg<_objref_HiroNX,HiroNX_Helper > HiroNX_out;

#endif

// interface HiroNX
class HiroNX {
public:
  // Declarations for this interface type.
  typedef HiroNX_ptr _ptr_type;
  typedef HiroNX_var _var_type;

  static _ptr_type _duplicate(_ptr_type);
  static _ptr_type _narrow(::CORBA::Object_ptr);
  static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
  
  static _ptr_type _nil();

  static inline void _marshalObjRef(_ptr_type, cdrStream&);

  static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
    omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
    if (o)
      return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
    else
      return _nil();
  }

  static inline _ptr_type _fromObjRef(omniObjRef* o) {
    if (o)
      return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
    else
      return _nil();
  }

  static _core_attr const char* _PD_repoId;

  // Other IDL defined within this scope.
  
};

class _objref_HiroNX :
  public virtual ::CORBA::Object,
  public virtual omniObjRef
{
public:
  // IDL operations
  void setupRobot();
  void restart();
  void goInitial();
  void goOffPose();
  void servoOn();
  void servoOff();
  void calibrateJoint();
  void servoOnHands();
  void servoOffHands();
  void EngageProtectiveStop();
  void DisengageProtectiveStop();
  void reboot();
  void shutdown();
  void rhandOpen();
  void rhandClose();
  void lhandOpen();
  void lhandClose();

  // Constructors
  inline _objref_HiroNX()  { _PR_setobj(0); }  // nil
  _objref_HiroNX(omniIOR*, omniIdentity*);

protected:
  virtual ~_objref_HiroNX();

  
private:
  virtual void* _ptrToObjRef(const char*);

  _objref_HiroNX(const _objref_HiroNX&);
  _objref_HiroNX& operator = (const _objref_HiroNX&);
  // not implemented

  friend class HiroNX;
};

class _pof_HiroNX : public _OMNI_NS(proxyObjectFactory) {
public:
  inline _pof_HiroNX() : _OMNI_NS(proxyObjectFactory)(HiroNX::_PD_repoId) {}
  virtual ~_pof_HiroNX();

  virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
  virtual _CORBA_Boolean is_a(const char*) const;
};

class _impl_HiroNX :
  public virtual omniServant
{
public:
  virtual ~_impl_HiroNX();

  virtual void setupRobot() = 0;
  virtual void restart() = 0;
  virtual void goInitial() = 0;
  virtual void goOffPose() = 0;
  virtual void servoOn() = 0;
  virtual void servoOff() = 0;
  virtual void calibrateJoint() = 0;
  virtual void servoOnHands() = 0;
  virtual void servoOffHands() = 0;
  virtual void EngageProtectiveStop() = 0;
  virtual void DisengageProtectiveStop() = 0;
  virtual void reboot() = 0;
  virtual void shutdown() = 0;
  virtual void rhandOpen() = 0;
  virtual void rhandClose() = 0;
  virtual void lhandOpen() = 0;
  virtual void lhandClose() = 0;
  
public:  // Really protected, workaround for xlC
  virtual _CORBA_Boolean _dispatch(omniCallHandle&);

private:
  virtual void* _ptrToInterface(const char*);
  virtual const char* _mostDerivedRepoId();
  
};


_CORBA_GLOBAL_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_HiroNX;



class POA_HiroNX :
  public virtual _impl_HiroNX,
  public virtual ::PortableServer::ServantBase
{
public:
  virtual ~POA_HiroNX();

  inline ::HiroNX_ptr _this() {
    return (::HiroNX_ptr) _do_this(::HiroNX::_PD_repoId);
  }
};







#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, HiroNX_ptr _s);
void operator<<=(::CORBA::Any& _a, HiroNX_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, HiroNX_ptr& _s);



inline void
HiroNX::_marshalObjRef(::HiroNX_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_HiroNX
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_HiroNX
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_HiroNX
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_HiroNX
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_HiroNX
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_HiroNX
#endif

#endif  // __HiroNX_hh__

