// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.

#include "ManipulatorCommonInterface_MiddleLevel.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_2;



void
RTC::CarPosWithElbow::operator>>= (cdrStream &_n) const
{
  
#ifndef OMNI_MIXED_ENDIAN_DOUBLE
  if (! _n.marshal_byte_swap()) {
    _n.put_octet_array((_CORBA_Octet*)(carPos),96,omni::ALIGN_8);
  }
  else 
#endif
  {
    _n.declareArrayLength(omni::ALIGN_8, 96);
    for (_CORBA_ULong _0i0 = 0; _0i0 < 3; _0i0++){
      for (_CORBA_ULong _0i1 = 0; _0i1 < 4; _0i1++){
        carPos[_0i0][_0i1] >>= _n;
      }
    }
  }
  elbow >>= _n;
  structFlag >>= _n;

}

void
RTC::CarPosWithElbow::operator<<= (cdrStream &_n)
{
  _n.unmarshalArrayDouble((_CORBA_Double*)(carPos), 12);
  (::CORBA::Double&)elbow <<= _n;
  (ULONG&)structFlag <<= _n;

}

void
RTC::CartesianSpeed::operator>>= (cdrStream &_n) const
{
  translation >>= _n;
  rotation >>= _n;

}

void
RTC::CartesianSpeed::operator<<= (cdrStream &_n)
{
  (::CORBA::Double&)translation <<= _n;
  (::CORBA::Double&)rotation <<= _n;

}

ManipulatorCommonInterface_Middle_ptr ManipulatorCommonInterface_Middle_Helper::_nil() {
  return ::ManipulatorCommonInterface_Middle::_nil();
}

::CORBA::Boolean ManipulatorCommonInterface_Middle_Helper::is_nil(::ManipulatorCommonInterface_Middle_ptr p) {
  return ::CORBA::is_nil(p);

}

void ManipulatorCommonInterface_Middle_Helper::release(::ManipulatorCommonInterface_Middle_ptr p) {
  ::CORBA::release(p);
}

void ManipulatorCommonInterface_Middle_Helper::marshalObjRef(::ManipulatorCommonInterface_Middle_ptr obj, cdrStream& s) {
  ::ManipulatorCommonInterface_Middle::_marshalObjRef(obj, s);
}

ManipulatorCommonInterface_Middle_ptr ManipulatorCommonInterface_Middle_Helper::unmarshalObjRef(cdrStream& s) {
  return ::ManipulatorCommonInterface_Middle::_unmarshalObjRef(s);
}

void ManipulatorCommonInterface_Middle_Helper::duplicate(::ManipulatorCommonInterface_Middle_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

ManipulatorCommonInterface_Middle_ptr
ManipulatorCommonInterface_Middle::_duplicate(::ManipulatorCommonInterface_Middle_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

ManipulatorCommonInterface_Middle_ptr
ManipulatorCommonInterface_Middle::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


ManipulatorCommonInterface_Middle_ptr
ManipulatorCommonInterface_Middle::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

ManipulatorCommonInterface_Middle_ptr
ManipulatorCommonInterface_Middle::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_ManipulatorCommonInterface_Middle _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_ManipulatorCommonInterface_Middle* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_ManipulatorCommonInterface_Middle;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* ManipulatorCommonInterface_Middle::_PD_repoId = "IDL:ManipulatorCommonInterface_Middle:1.0";


_objref_ManipulatorCommonInterface_Middle::~_objref_ManipulatorCommonInterface_Middle() {
  
}


_objref_ManipulatorCommonInterface_Middle::_objref_ManipulatorCommonInterface_Middle(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::ManipulatorCommonInterface_Middle::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
_objref_ManipulatorCommonInterface_Middle::_ptrToObjRef(const char* id)
{
  if (id == ::ManipulatorCommonInterface_Middle::_PD_repoId)
    return (::ManipulatorCommonInterface_Middle_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::ManipulatorCommonInterface_Middle::_PD_repoId))
    return (::ManipulatorCommonInterface_Middle_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for ManipulatorCommonInterface_Middle::closeGripper

// Proxy call descriptor class. Mangled signature:
//  _cRTC_mRETURN__ID
class _0RL_cd_e5cc9767023e3fa4_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_e5cc9767023e3fa4_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  RTC::RETURN_ID_var result;
};

void _0RL_cd_e5cc9767023e3fa4_00000000::marshalReturnedValues(cdrStream& _n)
{
  (const RTC::RETURN_ID&) result >>= _n;

}

void _0RL_cd_e5cc9767023e3fa4_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new RTC::RETURN_ID;
  (RTC::RETURN_ID&)result <<= _n;

}

const char* const _0RL_cd_e5cc9767023e3fa4_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_e5cc9767023e3fa4_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_e5cc9767023e3fa4_00000000* tcd = (_0RL_cd_e5cc9767023e3fa4_00000000*)cd;
  _impl_ManipulatorCommonInterface_Middle* impl = (_impl_ManipulatorCommonInterface_Middle*) svnt->_ptrToInterface(ManipulatorCommonInterface_Middle::_PD_repoId);
  tcd->result = impl->closeGripper();


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Middle::closeGripper()
{
  _0RL_cd_e5cc9767023e3fa4_00000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_10000000, "closeGripper", 13);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ManipulatorCommonInterface_Middle::getBaseOffset

// Proxy call descriptor class. Mangled signature:
//  _cRTC_mRETURN__ID_o_a3_a4_cdouble
class _0RL_cd_e5cc9767023e3fa4_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_e5cc9767023e3fa4_20000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  RTC::HgMatrix arg_0_;
  RTC::HgMatrix_slice* arg_0;
  RTC::RETURN_ID_var result;
};

void _0RL_cd_e5cc9767023e3fa4_20000000::marshalReturnedValues(cdrStream& _n)
{
  (const RTC::RETURN_ID&) result >>= _n;

#ifndef OMNI_MIXED_ENDIAN_DOUBLE
  if (! _n.marshal_byte_swap()) {
    _n.put_octet_array((_CORBA_Octet*)((RTC::HgMatrix_slice*)arg_0),96,omni::ALIGN_8);
  }
  else 
#endif
  {
    _n.declareArrayLength(omni::ALIGN_8, 96);
    for (_CORBA_ULong _0i0 = 0; _0i0 < 3; _0i0++){
      for (_CORBA_ULong _0i1 = 0; _0i1 < 4; _0i1++){
        arg_0[_0i0][_0i1] >>= _n;
      }
    }
  }

}

void _0RL_cd_e5cc9767023e3fa4_20000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new RTC::RETURN_ID;
  (RTC::RETURN_ID&)result <<= _n;
  _n.unmarshalArrayDouble((_CORBA_Double*)((RTC::HgMatrix_slice*)arg_0), 12);

}

const char* const _0RL_cd_e5cc9767023e3fa4_20000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_e5cc9767023e3fa4_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_e5cc9767023e3fa4_20000000* tcd = (_0RL_cd_e5cc9767023e3fa4_20000000*)cd;
  _impl_ManipulatorCommonInterface_Middle* impl = (_impl_ManipulatorCommonInterface_Middle*) svnt->_ptrToInterface(ManipulatorCommonInterface_Middle::_PD_repoId);
  tcd->result = impl->getBaseOffset(tcd->arg_0);


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Middle::getBaseOffset(::RTC::HgMatrix offset)
{
  _0RL_cd_e5cc9767023e3fa4_20000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_30000000, "getBaseOffset", 14);
  _call_desc.arg_0 = &offset[0];

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ManipulatorCommonInterface_Middle::getFeedbackPosCartesian

// Proxy call descriptor class. Mangled signature:
//  _cRTC_mRETURN__ID_o_cRTC_mCarPosWithElbow
class _0RL_cd_e5cc9767023e3fa4_40000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_e5cc9767023e3fa4_40000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  RTC::CarPosWithElbow arg_0_;
  RTC::CarPosWithElbow* arg_0;
  RTC::RETURN_ID_var result;
};

void _0RL_cd_e5cc9767023e3fa4_40000000::marshalReturnedValues(cdrStream& _n)
{
  (const RTC::RETURN_ID&) result >>= _n;
  (const RTC::CarPosWithElbow&) *arg_0 >>= _n;

}

void _0RL_cd_e5cc9767023e3fa4_40000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new RTC::RETURN_ID;
  (RTC::RETURN_ID&)result <<= _n;
  (RTC::CarPosWithElbow&)*arg_0 <<= _n;

}

const char* const _0RL_cd_e5cc9767023e3fa4_40000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_e5cc9767023e3fa4_50000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_e5cc9767023e3fa4_40000000* tcd = (_0RL_cd_e5cc9767023e3fa4_40000000*)cd;
  _impl_ManipulatorCommonInterface_Middle* impl = (_impl_ManipulatorCommonInterface_Middle*) svnt->_ptrToInterface(ManipulatorCommonInterface_Middle::_PD_repoId);
  tcd->result = impl->getFeedbackPosCartesian(*tcd->arg_0);


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Middle::getFeedbackPosCartesian(::RTC::CarPosWithElbow& pos)
{
  _0RL_cd_e5cc9767023e3fa4_40000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_50000000, "getFeedbackPosCartesian", 24);
  _call_desc.arg_0 = &(::RTC::CarPosWithElbow&) pos;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ManipulatorCommonInterface_Middle::getMaxSpeedCartesian

// Proxy call descriptor class. Mangled signature:
//  _cRTC_mRETURN__ID_o_cRTC_mCartesianSpeed
class _0RL_cd_e5cc9767023e3fa4_60000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_e5cc9767023e3fa4_60000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  RTC::CartesianSpeed arg_0_;
  RTC::CartesianSpeed* arg_0;
  RTC::RETURN_ID_var result;
};

void _0RL_cd_e5cc9767023e3fa4_60000000::marshalReturnedValues(cdrStream& _n)
{
  (const RTC::RETURN_ID&) result >>= _n;
  (const RTC::CartesianSpeed&) *arg_0 >>= _n;

}

void _0RL_cd_e5cc9767023e3fa4_60000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new RTC::RETURN_ID;
  (RTC::RETURN_ID&)result <<= _n;
  (RTC::CartesianSpeed&)*arg_0 <<= _n;

}

const char* const _0RL_cd_e5cc9767023e3fa4_60000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_e5cc9767023e3fa4_70000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_e5cc9767023e3fa4_60000000* tcd = (_0RL_cd_e5cc9767023e3fa4_60000000*)cd;
  _impl_ManipulatorCommonInterface_Middle* impl = (_impl_ManipulatorCommonInterface_Middle*) svnt->_ptrToInterface(ManipulatorCommonInterface_Middle::_PD_repoId);
  tcd->result = impl->getMaxSpeedCartesian(*tcd->arg_0);


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Middle::getMaxSpeedCartesian(::RTC::CartesianSpeed& speed)
{
  _0RL_cd_e5cc9767023e3fa4_60000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_70000000, "getMaxSpeedCartesian", 21);
  _call_desc.arg_0 = &(::RTC::CartesianSpeed&) speed;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ManipulatorCommonInterface_Middle::getMaxSpeedJoint

// Proxy call descriptor class. Mangled signature:
//  _cRTC_mRETURN__ID_o_cRTC_mDoubleSeq
class _0RL_cd_e5cc9767023e3fa4_80000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_e5cc9767023e3fa4_80000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  RTC::DoubleSeq_var arg_0;
  RTC::RETURN_ID_var result;
};

void _0RL_cd_e5cc9767023e3fa4_80000000::marshalReturnedValues(cdrStream& _n)
{
  (const RTC::RETURN_ID&) result >>= _n;
  (const RTC::DoubleSeq&) arg_0 >>= _n;

}

void _0RL_cd_e5cc9767023e3fa4_80000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new RTC::RETURN_ID;
  (RTC::RETURN_ID&)result <<= _n;
  arg_0 = new RTC::DoubleSeq;
  (RTC::DoubleSeq&)arg_0 <<= _n;

}

const char* const _0RL_cd_e5cc9767023e3fa4_80000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_e5cc9767023e3fa4_90000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_e5cc9767023e3fa4_80000000* tcd = (_0RL_cd_e5cc9767023e3fa4_80000000*)cd;
  _impl_ManipulatorCommonInterface_Middle* impl = (_impl_ManipulatorCommonInterface_Middle*) svnt->_ptrToInterface(ManipulatorCommonInterface_Middle::_PD_repoId);
  tcd->result = impl->getMaxSpeedJoint(tcd->arg_0.out());


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Middle::getMaxSpeedJoint(::RTC::DoubleSeq_out speed)
{
  _0RL_cd_e5cc9767023e3fa4_80000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_90000000, "getMaxSpeedJoint", 17);


  _invoke(_call_desc);
  speed = _call_desc.arg_0._retn();
  return _call_desc.result._retn();


}


//
// Code for ManipulatorCommonInterface_Middle::getMinAccelTimeCartesian

// Proxy call descriptor class. Mangled signature:
//  _cRTC_mRETURN__ID_o_cdouble
class _0RL_cd_e5cc9767023e3fa4_a0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_e5cc9767023e3fa4_a0000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Double arg_0;
  RTC::RETURN_ID_var result;
};

void _0RL_cd_e5cc9767023e3fa4_a0000000::marshalReturnedValues(cdrStream& _n)
{
  (const RTC::RETURN_ID&) result >>= _n;
  arg_0 >>= _n;

}

void _0RL_cd_e5cc9767023e3fa4_a0000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new RTC::RETURN_ID;
  (RTC::RETURN_ID&)result <<= _n;
  (::CORBA::Double&)arg_0 <<= _n;

}

const char* const _0RL_cd_e5cc9767023e3fa4_a0000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_e5cc9767023e3fa4_b0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_e5cc9767023e3fa4_a0000000* tcd = (_0RL_cd_e5cc9767023e3fa4_a0000000*)cd;
  _impl_ManipulatorCommonInterface_Middle* impl = (_impl_ManipulatorCommonInterface_Middle*) svnt->_ptrToInterface(ManipulatorCommonInterface_Middle::_PD_repoId);
  tcd->result = impl->getMinAccelTimeCartesian(tcd->arg_0);


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Middle::getMinAccelTimeCartesian(::CORBA::Double& aclTime)
{
  _0RL_cd_e5cc9767023e3fa4_a0000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_b0000000, "getMinAccelTimeCartesian", 25);


  _invoke(_call_desc);
  aclTime = _call_desc.arg_0;
  return _call_desc.result._retn();


}


//
// Code for ManipulatorCommonInterface_Middle::getMinAccelTimeJoint

// Local call call-back function.
static void
_0RL_lcfn_e5cc9767023e3fa4_c0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_e5cc9767023e3fa4_a0000000* tcd = (_0RL_cd_e5cc9767023e3fa4_a0000000*)cd;
  _impl_ManipulatorCommonInterface_Middle* impl = (_impl_ManipulatorCommonInterface_Middle*) svnt->_ptrToInterface(ManipulatorCommonInterface_Middle::_PD_repoId);
  tcd->result = impl->getMinAccelTimeJoint(tcd->arg_0);


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Middle::getMinAccelTimeJoint(::CORBA::Double& aclTime)
{
  _0RL_cd_e5cc9767023e3fa4_a0000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_c0000000, "getMinAccelTimeJoint", 21);


  _invoke(_call_desc);
  aclTime = _call_desc.arg_0;
  return _call_desc.result._retn();


}


//
// Code for ManipulatorCommonInterface_Middle::getSoftLimitCartesian

// Proxy call descriptor class. Mangled signature:
//  _cRTC_mRETURN__ID_o_cRTC_mLimitValue_o_cRTC_mLimitValue_o_cRTC_mLimitValue
class _0RL_cd_e5cc9767023e3fa4_d0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_e5cc9767023e3fa4_d0000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  RTC::LimitValue arg_0_;
  RTC::LimitValue* arg_0;
  RTC::LimitValue arg_1_;
  RTC::LimitValue* arg_1;
  RTC::LimitValue arg_2_;
  RTC::LimitValue* arg_2;
  RTC::RETURN_ID_var result;
};

void _0RL_cd_e5cc9767023e3fa4_d0000000::marshalReturnedValues(cdrStream& _n)
{
  (const RTC::RETURN_ID&) result >>= _n;
  (const RTC::LimitValue&) *arg_0 >>= _n;
  (const RTC::LimitValue&) *arg_1 >>= _n;
  (const RTC::LimitValue&) *arg_2 >>= _n;

}

void _0RL_cd_e5cc9767023e3fa4_d0000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new RTC::RETURN_ID;
  (RTC::RETURN_ID&)result <<= _n;
  (RTC::LimitValue&)*arg_0 <<= _n;
  (RTC::LimitValue&)*arg_1 <<= _n;
  (RTC::LimitValue&)*arg_2 <<= _n;

}

const char* const _0RL_cd_e5cc9767023e3fa4_d0000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_e5cc9767023e3fa4_e0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_e5cc9767023e3fa4_d0000000* tcd = (_0RL_cd_e5cc9767023e3fa4_d0000000*)cd;
  _impl_ManipulatorCommonInterface_Middle* impl = (_impl_ManipulatorCommonInterface_Middle*) svnt->_ptrToInterface(ManipulatorCommonInterface_Middle::_PD_repoId);
  tcd->result = impl->getSoftLimitCartesian(*tcd->arg_0, *tcd->arg_1, *tcd->arg_2);


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Middle::getSoftLimitCartesian(::RTC::LimitValue& xLimit, ::RTC::LimitValue& yLimit, ::RTC::LimitValue& zLimit)
{
  _0RL_cd_e5cc9767023e3fa4_d0000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_e0000000, "getSoftLimitCartesian", 22);
  _call_desc.arg_0 = &(::RTC::LimitValue&) xLimit;
  _call_desc.arg_1 = &(::RTC::LimitValue&) yLimit;
  _call_desc.arg_2 = &(::RTC::LimitValue&) zLimit;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ManipulatorCommonInterface_Middle::moveGripper

// Proxy call descriptor class. Mangled signature:
//  _cRTC_mRETURN__ID_i_cunsigned_plong
class _0RL_cd_e5cc9767023e3fa4_f0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_e5cc9767023e3fa4_f0000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  RTC::ULONG arg_0;
  RTC::RETURN_ID_var result;
};

void _0RL_cd_e5cc9767023e3fa4_f0000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_e5cc9767023e3fa4_f0000000::unmarshalArguments(cdrStream& _n)
{
  (RTC::ULONG&)arg_0 <<= _n;

}

void _0RL_cd_e5cc9767023e3fa4_f0000000::marshalReturnedValues(cdrStream& _n)
{
  (const RTC::RETURN_ID&) result >>= _n;

}

void _0RL_cd_e5cc9767023e3fa4_f0000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new RTC::RETURN_ID;
  (RTC::RETURN_ID&)result <<= _n;

}

const char* const _0RL_cd_e5cc9767023e3fa4_f0000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_e5cc9767023e3fa4_01000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_e5cc9767023e3fa4_f0000000* tcd = (_0RL_cd_e5cc9767023e3fa4_f0000000*)cd;
  _impl_ManipulatorCommonInterface_Middle* impl = (_impl_ManipulatorCommonInterface_Middle*) svnt->_ptrToInterface(ManipulatorCommonInterface_Middle::_PD_repoId);
  tcd->result = impl->moveGripper(tcd->arg_0);


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Middle::moveGripper(::RTC::ULONG angleRatio)
{
  _0RL_cd_e5cc9767023e3fa4_f0000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_01000000, "moveGripper", 12);
  _call_desc.arg_0 = angleRatio;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ManipulatorCommonInterface_Middle::moveLinearCartesianAbs

// Proxy call descriptor class. Mangled signature:
//  _cRTC_mRETURN__ID_i_cRTC_mCarPosWithElbow
class _0RL_cd_e5cc9767023e3fa4_11000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_e5cc9767023e3fa4_11000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  RTC::CarPosWithElbow arg_0_;
  const RTC::CarPosWithElbow* arg_0;
  RTC::RETURN_ID_var result;
};

void _0RL_cd_e5cc9767023e3fa4_11000000::marshalArguments(cdrStream& _n)
{
  (const RTC::CarPosWithElbow&) *arg_0 >>= _n;

}

void _0RL_cd_e5cc9767023e3fa4_11000000::unmarshalArguments(cdrStream& _n)
{
  (RTC::CarPosWithElbow&)arg_0_ <<= _n;
  arg_0 = &arg_0_;

}

void _0RL_cd_e5cc9767023e3fa4_11000000::marshalReturnedValues(cdrStream& _n)
{
  (const RTC::RETURN_ID&) result >>= _n;

}

void _0RL_cd_e5cc9767023e3fa4_11000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new RTC::RETURN_ID;
  (RTC::RETURN_ID&)result <<= _n;

}

const char* const _0RL_cd_e5cc9767023e3fa4_11000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_e5cc9767023e3fa4_21000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_e5cc9767023e3fa4_11000000* tcd = (_0RL_cd_e5cc9767023e3fa4_11000000*)cd;
  _impl_ManipulatorCommonInterface_Middle* impl = (_impl_ManipulatorCommonInterface_Middle*) svnt->_ptrToInterface(ManipulatorCommonInterface_Middle::_PD_repoId);
  tcd->result = impl->moveLinearCartesianAbs(*tcd->arg_0);


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Middle::moveLinearCartesianAbs(const ::RTC::CarPosWithElbow& carPoint)
{
  _0RL_cd_e5cc9767023e3fa4_11000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_21000000, "moveLinearCartesianAbs", 23);
  _call_desc.arg_0 = &(::RTC::CarPosWithElbow&) carPoint;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ManipulatorCommonInterface_Middle::moveLinearCartesianRel

// Local call call-back function.
static void
_0RL_lcfn_e5cc9767023e3fa4_31000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_e5cc9767023e3fa4_11000000* tcd = (_0RL_cd_e5cc9767023e3fa4_11000000*)cd;
  _impl_ManipulatorCommonInterface_Middle* impl = (_impl_ManipulatorCommonInterface_Middle*) svnt->_ptrToInterface(ManipulatorCommonInterface_Middle::_PD_repoId);
  tcd->result = impl->moveLinearCartesianRel(*tcd->arg_0);


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Middle::moveLinearCartesianRel(const ::RTC::CarPosWithElbow& carPoint)
{
  _0RL_cd_e5cc9767023e3fa4_11000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_31000000, "moveLinearCartesianRel", 23);
  _call_desc.arg_0 = &(::RTC::CarPosWithElbow&) carPoint;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ManipulatorCommonInterface_Middle::movePTPCartesianAbs

// Local call call-back function.
static void
_0RL_lcfn_e5cc9767023e3fa4_41000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_e5cc9767023e3fa4_11000000* tcd = (_0RL_cd_e5cc9767023e3fa4_11000000*)cd;
  _impl_ManipulatorCommonInterface_Middle* impl = (_impl_ManipulatorCommonInterface_Middle*) svnt->_ptrToInterface(ManipulatorCommonInterface_Middle::_PD_repoId);
  tcd->result = impl->movePTPCartesianAbs(*tcd->arg_0);


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Middle::movePTPCartesianAbs(const ::RTC::CarPosWithElbow& carPoint)
{
  _0RL_cd_e5cc9767023e3fa4_11000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_41000000, "movePTPCartesianAbs", 20);
  _call_desc.arg_0 = &(::RTC::CarPosWithElbow&) carPoint;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ManipulatorCommonInterface_Middle::movePTPCartesianRel

// Local call call-back function.
static void
_0RL_lcfn_e5cc9767023e3fa4_51000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_e5cc9767023e3fa4_11000000* tcd = (_0RL_cd_e5cc9767023e3fa4_11000000*)cd;
  _impl_ManipulatorCommonInterface_Middle* impl = (_impl_ManipulatorCommonInterface_Middle*) svnt->_ptrToInterface(ManipulatorCommonInterface_Middle::_PD_repoId);
  tcd->result = impl->movePTPCartesianRel(*tcd->arg_0);


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Middle::movePTPCartesianRel(const ::RTC::CarPosWithElbow& carPoint)
{
  _0RL_cd_e5cc9767023e3fa4_11000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_51000000, "movePTPCartesianRel", 20);
  _call_desc.arg_0 = &(::RTC::CarPosWithElbow&) carPoint;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ManipulatorCommonInterface_Middle::movePTPJointAbs

// Proxy call descriptor class. Mangled signature:
//  _cRTC_mRETURN__ID_i_cRTC_mJointPos
class _0RL_cd_e5cc9767023e3fa4_61000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_e5cc9767023e3fa4_61000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  RTC::JointPos_var arg_0_;
  const RTC::JointPos* arg_0;
  RTC::RETURN_ID_var result;
};

void _0RL_cd_e5cc9767023e3fa4_61000000::marshalArguments(cdrStream& _n)
{
  (const RTC::JointPos&) *arg_0 >>= _n;

}

void _0RL_cd_e5cc9767023e3fa4_61000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = new RTC::JointPos;
  (RTC::JointPos&)arg_0_ <<= _n;
  arg_0 = &arg_0_.in();

}

void _0RL_cd_e5cc9767023e3fa4_61000000::marshalReturnedValues(cdrStream& _n)
{
  (const RTC::RETURN_ID&) result >>= _n;

}

void _0RL_cd_e5cc9767023e3fa4_61000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new RTC::RETURN_ID;
  (RTC::RETURN_ID&)result <<= _n;

}

const char* const _0RL_cd_e5cc9767023e3fa4_61000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_e5cc9767023e3fa4_71000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_e5cc9767023e3fa4_61000000* tcd = (_0RL_cd_e5cc9767023e3fa4_61000000*)cd;
  _impl_ManipulatorCommonInterface_Middle* impl = (_impl_ManipulatorCommonInterface_Middle*) svnt->_ptrToInterface(ManipulatorCommonInterface_Middle::_PD_repoId);
  tcd->result = impl->movePTPJointAbs(*tcd->arg_0);


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Middle::movePTPJointAbs(const ::RTC::JointPos& jointPoints)
{
  _0RL_cd_e5cc9767023e3fa4_61000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_71000000, "movePTPJointAbs", 16);
  _call_desc.arg_0 = &(::RTC::JointPos&) jointPoints;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ManipulatorCommonInterface_Middle::movePTPJointRel

// Local call call-back function.
static void
_0RL_lcfn_e5cc9767023e3fa4_81000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_e5cc9767023e3fa4_61000000* tcd = (_0RL_cd_e5cc9767023e3fa4_61000000*)cd;
  _impl_ManipulatorCommonInterface_Middle* impl = (_impl_ManipulatorCommonInterface_Middle*) svnt->_ptrToInterface(ManipulatorCommonInterface_Middle::_PD_repoId);
  tcd->result = impl->movePTPJointRel(*tcd->arg_0);


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Middle::movePTPJointRel(const ::RTC::JointPos& jointPoints)
{
  _0RL_cd_e5cc9767023e3fa4_61000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_81000000, "movePTPJointRel", 16);
  _call_desc.arg_0 = &(::RTC::JointPos&) jointPoints;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ManipulatorCommonInterface_Middle::openGripper

// Local call call-back function.
static void
_0RL_lcfn_e5cc9767023e3fa4_91000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_e5cc9767023e3fa4_00000000* tcd = (_0RL_cd_e5cc9767023e3fa4_00000000*)cd;
  _impl_ManipulatorCommonInterface_Middle* impl = (_impl_ManipulatorCommonInterface_Middle*) svnt->_ptrToInterface(ManipulatorCommonInterface_Middle::_PD_repoId);
  tcd->result = impl->openGripper();


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Middle::openGripper()
{
  _0RL_cd_e5cc9767023e3fa4_00000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_91000000, "openGripper", 12);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ManipulatorCommonInterface_Middle::pause

// Local call call-back function.
static void
_0RL_lcfn_e5cc9767023e3fa4_a1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_e5cc9767023e3fa4_00000000* tcd = (_0RL_cd_e5cc9767023e3fa4_00000000*)cd;
  _impl_ManipulatorCommonInterface_Middle* impl = (_impl_ManipulatorCommonInterface_Middle*) svnt->_ptrToInterface(ManipulatorCommonInterface_Middle::_PD_repoId);
  tcd->result = impl->pause();


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Middle::pause()
{
  _0RL_cd_e5cc9767023e3fa4_00000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_a1000000, "pause", 6);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ManipulatorCommonInterface_Middle::resume

// Local call call-back function.
static void
_0RL_lcfn_e5cc9767023e3fa4_b1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_e5cc9767023e3fa4_00000000* tcd = (_0RL_cd_e5cc9767023e3fa4_00000000*)cd;
  _impl_ManipulatorCommonInterface_Middle* impl = (_impl_ManipulatorCommonInterface_Middle*) svnt->_ptrToInterface(ManipulatorCommonInterface_Middle::_PD_repoId);
  tcd->result = impl->resume();


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Middle::resume()
{
  _0RL_cd_e5cc9767023e3fa4_00000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_b1000000, "resume", 7);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ManipulatorCommonInterface_Middle::stop

// Local call call-back function.
static void
_0RL_lcfn_e5cc9767023e3fa4_c1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_e5cc9767023e3fa4_00000000* tcd = (_0RL_cd_e5cc9767023e3fa4_00000000*)cd;
  _impl_ManipulatorCommonInterface_Middle* impl = (_impl_ManipulatorCommonInterface_Middle*) svnt->_ptrToInterface(ManipulatorCommonInterface_Middle::_PD_repoId);
  tcd->result = impl->stop();


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Middle::stop()
{
  _0RL_cd_e5cc9767023e3fa4_00000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_c1000000, "stop", 5);


  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ManipulatorCommonInterface_Middle::setAccelTimeCartesian

// Proxy call descriptor class. Mangled signature:
//  _cRTC_mRETURN__ID_i_cdouble
class _0RL_cd_e5cc9767023e3fa4_d1000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_e5cc9767023e3fa4_d1000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Double arg_0;
  RTC::RETURN_ID_var result;
};

void _0RL_cd_e5cc9767023e3fa4_d1000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_e5cc9767023e3fa4_d1000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Double&)arg_0 <<= _n;

}

void _0RL_cd_e5cc9767023e3fa4_d1000000::marshalReturnedValues(cdrStream& _n)
{
  (const RTC::RETURN_ID&) result >>= _n;

}

void _0RL_cd_e5cc9767023e3fa4_d1000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new RTC::RETURN_ID;
  (RTC::RETURN_ID&)result <<= _n;

}

const char* const _0RL_cd_e5cc9767023e3fa4_d1000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_e5cc9767023e3fa4_e1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_e5cc9767023e3fa4_d1000000* tcd = (_0RL_cd_e5cc9767023e3fa4_d1000000*)cd;
  _impl_ManipulatorCommonInterface_Middle* impl = (_impl_ManipulatorCommonInterface_Middle*) svnt->_ptrToInterface(ManipulatorCommonInterface_Middle::_PD_repoId);
  tcd->result = impl->setAccelTimeCartesian(tcd->arg_0);


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Middle::setAccelTimeCartesian(::CORBA::Double aclTime)
{
  _0RL_cd_e5cc9767023e3fa4_d1000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_e1000000, "setAccelTimeCartesian", 22);
  _call_desc.arg_0 = aclTime;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ManipulatorCommonInterface_Middle::setAccelTimeJoint

// Local call call-back function.
static void
_0RL_lcfn_e5cc9767023e3fa4_f1000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_e5cc9767023e3fa4_d1000000* tcd = (_0RL_cd_e5cc9767023e3fa4_d1000000*)cd;
  _impl_ManipulatorCommonInterface_Middle* impl = (_impl_ManipulatorCommonInterface_Middle*) svnt->_ptrToInterface(ManipulatorCommonInterface_Middle::_PD_repoId);
  tcd->result = impl->setAccelTimeJoint(tcd->arg_0);


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Middle::setAccelTimeJoint(::CORBA::Double aclTime)
{
  _0RL_cd_e5cc9767023e3fa4_d1000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_f1000000, "setAccelTimeJoint", 18);
  _call_desc.arg_0 = aclTime;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ManipulatorCommonInterface_Middle::setBaseOffset

// Proxy call descriptor class. Mangled signature:
//  _cRTC_mRETURN__ID_i_a3_a4_cdouble
class _0RL_cd_e5cc9767023e3fa4_02000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_e5cc9767023e3fa4_02000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  RTC::HgMatrix arg_0_;
  const RTC::HgMatrix_slice* arg_0;
  RTC::RETURN_ID_var result;
};

void _0RL_cd_e5cc9767023e3fa4_02000000::marshalArguments(cdrStream& _n)
{
  
#ifndef OMNI_MIXED_ENDIAN_DOUBLE
  if (! _n.marshal_byte_swap()) {
    _n.put_octet_array((_CORBA_Octet*)((RTC::HgMatrix_slice*)arg_0),96,omni::ALIGN_8);
  }
  else 
#endif
  {
    _n.declareArrayLength(omni::ALIGN_8, 96);
    for (_CORBA_ULong _0i0 = 0; _0i0 < 3; _0i0++){
      for (_CORBA_ULong _0i1 = 0; _0i1 < 4; _0i1++){
        arg_0[_0i0][_0i1] >>= _n;
      }
    }
  }

}

void _0RL_cd_e5cc9767023e3fa4_02000000::unmarshalArguments(cdrStream& _n)
{
  _n.unmarshalArrayDouble((_CORBA_Double*)((RTC::HgMatrix_slice*)arg_0_), 12);
  arg_0 = &arg_0_[0];

}

void _0RL_cd_e5cc9767023e3fa4_02000000::marshalReturnedValues(cdrStream& _n)
{
  (const RTC::RETURN_ID&) result >>= _n;

}

void _0RL_cd_e5cc9767023e3fa4_02000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new RTC::RETURN_ID;
  (RTC::RETURN_ID&)result <<= _n;

}

const char* const _0RL_cd_e5cc9767023e3fa4_02000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_e5cc9767023e3fa4_12000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_e5cc9767023e3fa4_02000000* tcd = (_0RL_cd_e5cc9767023e3fa4_02000000*)cd;
  _impl_ManipulatorCommonInterface_Middle* impl = (_impl_ManipulatorCommonInterface_Middle*) svnt->_ptrToInterface(ManipulatorCommonInterface_Middle::_PD_repoId);
  tcd->result = impl->setBaseOffset(tcd->arg_0);


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Middle::setBaseOffset(const ::RTC::HgMatrix offset)
{
  _0RL_cd_e5cc9767023e3fa4_02000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_12000000, "setBaseOffset", 14);
  _call_desc.arg_0 = &offset[0];

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ManipulatorCommonInterface_Middle::setControlPointOffset

// Local call call-back function.
static void
_0RL_lcfn_e5cc9767023e3fa4_22000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_e5cc9767023e3fa4_02000000* tcd = (_0RL_cd_e5cc9767023e3fa4_02000000*)cd;
  _impl_ManipulatorCommonInterface_Middle* impl = (_impl_ManipulatorCommonInterface_Middle*) svnt->_ptrToInterface(ManipulatorCommonInterface_Middle::_PD_repoId);
  tcd->result = impl->setControlPointOffset(tcd->arg_0);


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Middle::setControlPointOffset(const ::RTC::HgMatrix offset)
{
  _0RL_cd_e5cc9767023e3fa4_02000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_22000000, "setControlPointOffset", 22);
  _call_desc.arg_0 = &offset[0];

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ManipulatorCommonInterface_Middle::setMaxSpeedCartesian

// Proxy call descriptor class. Mangled signature:
//  _cRTC_mRETURN__ID_i_cRTC_mCartesianSpeed
class _0RL_cd_e5cc9767023e3fa4_32000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_e5cc9767023e3fa4_32000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  RTC::CartesianSpeed arg_0_;
  const RTC::CartesianSpeed* arg_0;
  RTC::RETURN_ID_var result;
};

void _0RL_cd_e5cc9767023e3fa4_32000000::marshalArguments(cdrStream& _n)
{
  (const RTC::CartesianSpeed&) *arg_0 >>= _n;

}

void _0RL_cd_e5cc9767023e3fa4_32000000::unmarshalArguments(cdrStream& _n)
{
  (RTC::CartesianSpeed&)arg_0_ <<= _n;
  arg_0 = &arg_0_;

}

void _0RL_cd_e5cc9767023e3fa4_32000000::marshalReturnedValues(cdrStream& _n)
{
  (const RTC::RETURN_ID&) result >>= _n;

}

void _0RL_cd_e5cc9767023e3fa4_32000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new RTC::RETURN_ID;
  (RTC::RETURN_ID&)result <<= _n;

}

const char* const _0RL_cd_e5cc9767023e3fa4_32000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_e5cc9767023e3fa4_42000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_e5cc9767023e3fa4_32000000* tcd = (_0RL_cd_e5cc9767023e3fa4_32000000*)cd;
  _impl_ManipulatorCommonInterface_Middle* impl = (_impl_ManipulatorCommonInterface_Middle*) svnt->_ptrToInterface(ManipulatorCommonInterface_Middle::_PD_repoId);
  tcd->result = impl->setMaxSpeedCartesian(*tcd->arg_0);


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Middle::setMaxSpeedCartesian(const ::RTC::CartesianSpeed& speed)
{
  _0RL_cd_e5cc9767023e3fa4_32000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_42000000, "setMaxSpeedCartesian", 21);
  _call_desc.arg_0 = &(::RTC::CartesianSpeed&) speed;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ManipulatorCommonInterface_Middle::setMaxSpeedJoint

// Proxy call descriptor class. Mangled signature:
//  _cRTC_mRETURN__ID_i_cRTC_mDoubleSeq
class _0RL_cd_e5cc9767023e3fa4_52000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_e5cc9767023e3fa4_52000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  RTC::DoubleSeq_var arg_0_;
  const RTC::DoubleSeq* arg_0;
  RTC::RETURN_ID_var result;
};

void _0RL_cd_e5cc9767023e3fa4_52000000::marshalArguments(cdrStream& _n)
{
  (const RTC::DoubleSeq&) *arg_0 >>= _n;

}

void _0RL_cd_e5cc9767023e3fa4_52000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = new RTC::DoubleSeq;
  (RTC::DoubleSeq&)arg_0_ <<= _n;
  arg_0 = &arg_0_.in();

}

void _0RL_cd_e5cc9767023e3fa4_52000000::marshalReturnedValues(cdrStream& _n)
{
  (const RTC::RETURN_ID&) result >>= _n;

}

void _0RL_cd_e5cc9767023e3fa4_52000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new RTC::RETURN_ID;
  (RTC::RETURN_ID&)result <<= _n;

}

const char* const _0RL_cd_e5cc9767023e3fa4_52000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_e5cc9767023e3fa4_62000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_e5cc9767023e3fa4_52000000* tcd = (_0RL_cd_e5cc9767023e3fa4_52000000*)cd;
  _impl_ManipulatorCommonInterface_Middle* impl = (_impl_ManipulatorCommonInterface_Middle*) svnt->_ptrToInterface(ManipulatorCommonInterface_Middle::_PD_repoId);
  tcd->result = impl->setMaxSpeedJoint(*tcd->arg_0);


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Middle::setMaxSpeedJoint(const ::RTC::DoubleSeq& speed)
{
  _0RL_cd_e5cc9767023e3fa4_52000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_62000000, "setMaxSpeedJoint", 17);
  _call_desc.arg_0 = &(::RTC::DoubleSeq&) speed;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ManipulatorCommonInterface_Middle::setMinAccelTimeCartesian

// Local call call-back function.
static void
_0RL_lcfn_e5cc9767023e3fa4_72000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_e5cc9767023e3fa4_d1000000* tcd = (_0RL_cd_e5cc9767023e3fa4_d1000000*)cd;
  _impl_ManipulatorCommonInterface_Middle* impl = (_impl_ManipulatorCommonInterface_Middle*) svnt->_ptrToInterface(ManipulatorCommonInterface_Middle::_PD_repoId);
  tcd->result = impl->setMinAccelTimeCartesian(tcd->arg_0);


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Middle::setMinAccelTimeCartesian(::CORBA::Double aclTime)
{
  _0RL_cd_e5cc9767023e3fa4_d1000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_72000000, "setMinAccelTimeCartesian", 25);
  _call_desc.arg_0 = aclTime;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ManipulatorCommonInterface_Middle::setMinAccelTimeJoint

// Local call call-back function.
static void
_0RL_lcfn_e5cc9767023e3fa4_82000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_e5cc9767023e3fa4_d1000000* tcd = (_0RL_cd_e5cc9767023e3fa4_d1000000*)cd;
  _impl_ManipulatorCommonInterface_Middle* impl = (_impl_ManipulatorCommonInterface_Middle*) svnt->_ptrToInterface(ManipulatorCommonInterface_Middle::_PD_repoId);
  tcd->result = impl->setMinAccelTimeJoint(tcd->arg_0);


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Middle::setMinAccelTimeJoint(::CORBA::Double aclTime)
{
  _0RL_cd_e5cc9767023e3fa4_d1000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_82000000, "setMinAccelTimeJoint", 21);
  _call_desc.arg_0 = aclTime;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ManipulatorCommonInterface_Middle::setSoftLimitCartesian

// Proxy call descriptor class. Mangled signature:
//  _cRTC_mRETURN__ID_i_cRTC_mLimitValue_i_cRTC_mLimitValue_i_cRTC_mLimitValue
class _0RL_cd_e5cc9767023e3fa4_92000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_e5cc9767023e3fa4_92000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  RTC::LimitValue arg_0_;
  const RTC::LimitValue* arg_0;
  RTC::LimitValue arg_1_;
  const RTC::LimitValue* arg_1;
  RTC::LimitValue arg_2_;
  const RTC::LimitValue* arg_2;
  RTC::RETURN_ID_var result;
};

void _0RL_cd_e5cc9767023e3fa4_92000000::marshalArguments(cdrStream& _n)
{
  (const RTC::LimitValue&) *arg_0 >>= _n;
  (const RTC::LimitValue&) *arg_1 >>= _n;
  (const RTC::LimitValue&) *arg_2 >>= _n;

}

void _0RL_cd_e5cc9767023e3fa4_92000000::unmarshalArguments(cdrStream& _n)
{
  (RTC::LimitValue&)arg_0_ <<= _n;
  arg_0 = &arg_0_;
  (RTC::LimitValue&)arg_1_ <<= _n;
  arg_1 = &arg_1_;
  (RTC::LimitValue&)arg_2_ <<= _n;
  arg_2 = &arg_2_;

}

void _0RL_cd_e5cc9767023e3fa4_92000000::marshalReturnedValues(cdrStream& _n)
{
  (const RTC::RETURN_ID&) result >>= _n;

}

void _0RL_cd_e5cc9767023e3fa4_92000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = new RTC::RETURN_ID;
  (RTC::RETURN_ID&)result <<= _n;

}

const char* const _0RL_cd_e5cc9767023e3fa4_92000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_e5cc9767023e3fa4_a2000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_e5cc9767023e3fa4_92000000* tcd = (_0RL_cd_e5cc9767023e3fa4_92000000*)cd;
  _impl_ManipulatorCommonInterface_Middle* impl = (_impl_ManipulatorCommonInterface_Middle*) svnt->_ptrToInterface(ManipulatorCommonInterface_Middle::_PD_repoId);
  tcd->result = impl->setSoftLimitCartesian(*tcd->arg_0, *tcd->arg_1, *tcd->arg_2);


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Middle::setSoftLimitCartesian(const ::RTC::LimitValue& xLimit, const ::RTC::LimitValue& yLimit, const ::RTC::LimitValue& zLimit)
{
  _0RL_cd_e5cc9767023e3fa4_92000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_a2000000, "setSoftLimitCartesian", 22);
  _call_desc.arg_0 = &(::RTC::LimitValue&) xLimit;
  _call_desc.arg_1 = &(::RTC::LimitValue&) yLimit;
  _call_desc.arg_2 = &(::RTC::LimitValue&) zLimit;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ManipulatorCommonInterface_Middle::setSpeedCartesian

// Local call call-back function.
static void
_0RL_lcfn_e5cc9767023e3fa4_b2000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_e5cc9767023e3fa4_f0000000* tcd = (_0RL_cd_e5cc9767023e3fa4_f0000000*)cd;
  _impl_ManipulatorCommonInterface_Middle* impl = (_impl_ManipulatorCommonInterface_Middle*) svnt->_ptrToInterface(ManipulatorCommonInterface_Middle::_PD_repoId);
  tcd->result = impl->setSpeedCartesian(tcd->arg_0);


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Middle::setSpeedCartesian(::RTC::ULONG spdRatio)
{
  _0RL_cd_e5cc9767023e3fa4_f0000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_b2000000, "setSpeedCartesian", 18);
  _call_desc.arg_0 = spdRatio;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}


//
// Code for ManipulatorCommonInterface_Middle::setSpeedJoint

// Local call call-back function.
static void
_0RL_lcfn_e5cc9767023e3fa4_c2000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_e5cc9767023e3fa4_f0000000* tcd = (_0RL_cd_e5cc9767023e3fa4_f0000000*)cd;
  _impl_ManipulatorCommonInterface_Middle* impl = (_impl_ManipulatorCommonInterface_Middle*) svnt->_ptrToInterface(ManipulatorCommonInterface_Middle::_PD_repoId);
  tcd->result = impl->setSpeedJoint(tcd->arg_0);


}

RTC::RETURN_ID* _objref_ManipulatorCommonInterface_Middle::setSpeedJoint(::RTC::ULONG spdRatio)
{
  _0RL_cd_e5cc9767023e3fa4_f0000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_c2000000, "setSpeedJoint", 14);
  _call_desc.arg_0 = spdRatio;

  _invoke(_call_desc);
  return _call_desc.result._retn();


}

_pof_ManipulatorCommonInterface_Middle::~_pof_ManipulatorCommonInterface_Middle() {}


omniObjRef*
_pof_ManipulatorCommonInterface_Middle::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::_objref_ManipulatorCommonInterface_Middle(ior, id);
}


::CORBA::Boolean
_pof_ManipulatorCommonInterface_Middle::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::ManipulatorCommonInterface_Middle::_PD_repoId))
    return 1;
  
  return 0;
}

const _pof_ManipulatorCommonInterface_Middle _the_pof_ManipulatorCommonInterface__Middle;

_impl_ManipulatorCommonInterface_Middle::~_impl_ManipulatorCommonInterface_Middle() {}


::CORBA::Boolean
_impl_ManipulatorCommonInterface_Middle::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "closeGripper")) {

    _0RL_cd_e5cc9767023e3fa4_00000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_10000000, "closeGripper", 13, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "getBaseOffset")) {

    _0RL_cd_e5cc9767023e3fa4_20000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_30000000, "getBaseOffset", 14, 1);
    _call_desc.arg_0 = _call_desc.arg_0_;
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "getFeedbackPosCartesian")) {

    _0RL_cd_e5cc9767023e3fa4_40000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_50000000, "getFeedbackPosCartesian", 24, 1);
    _call_desc.arg_0 = &_call_desc.arg_0_;
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "getMaxSpeedCartesian")) {

    _0RL_cd_e5cc9767023e3fa4_60000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_70000000, "getMaxSpeedCartesian", 21, 1);
    _call_desc.arg_0 = &_call_desc.arg_0_;
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "getMaxSpeedJoint")) {

    _0RL_cd_e5cc9767023e3fa4_80000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_90000000, "getMaxSpeedJoint", 17, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "getMinAccelTimeCartesian")) {

    _0RL_cd_e5cc9767023e3fa4_a0000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_b0000000, "getMinAccelTimeCartesian", 25, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "getMinAccelTimeJoint")) {

    _0RL_cd_e5cc9767023e3fa4_a0000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_c0000000, "getMinAccelTimeJoint", 21, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "getSoftLimitCartesian")) {

    _0RL_cd_e5cc9767023e3fa4_d0000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_e0000000, "getSoftLimitCartesian", 22, 1);
    _call_desc.arg_0 = &_call_desc.arg_0_;
    _call_desc.arg_1 = &_call_desc.arg_1_;
    _call_desc.arg_2 = &_call_desc.arg_2_;
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "moveGripper")) {

    _0RL_cd_e5cc9767023e3fa4_f0000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_01000000, "moveGripper", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "moveLinearCartesianAbs")) {

    _0RL_cd_e5cc9767023e3fa4_11000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_21000000, "moveLinearCartesianAbs", 23, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "moveLinearCartesianRel")) {

    _0RL_cd_e5cc9767023e3fa4_11000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_31000000, "moveLinearCartesianRel", 23, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "movePTPCartesianAbs")) {

    _0RL_cd_e5cc9767023e3fa4_11000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_41000000, "movePTPCartesianAbs", 20, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "movePTPCartesianRel")) {

    _0RL_cd_e5cc9767023e3fa4_11000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_51000000, "movePTPCartesianRel", 20, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "movePTPJointAbs")) {

    _0RL_cd_e5cc9767023e3fa4_61000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_71000000, "movePTPJointAbs", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "movePTPJointRel")) {

    _0RL_cd_e5cc9767023e3fa4_61000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_81000000, "movePTPJointRel", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "openGripper")) {

    _0RL_cd_e5cc9767023e3fa4_00000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_91000000, "openGripper", 12, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "pause")) {

    _0RL_cd_e5cc9767023e3fa4_00000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_a1000000, "pause", 6, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "resume")) {

    _0RL_cd_e5cc9767023e3fa4_00000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_b1000000, "resume", 7, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "stop")) {

    _0RL_cd_e5cc9767023e3fa4_00000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_c1000000, "stop", 5, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "setAccelTimeCartesian")) {

    _0RL_cd_e5cc9767023e3fa4_d1000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_e1000000, "setAccelTimeCartesian", 22, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "setAccelTimeJoint")) {

    _0RL_cd_e5cc9767023e3fa4_d1000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_f1000000, "setAccelTimeJoint", 18, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "setBaseOffset")) {

    _0RL_cd_e5cc9767023e3fa4_02000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_12000000, "setBaseOffset", 14, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "setControlPointOffset")) {

    _0RL_cd_e5cc9767023e3fa4_02000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_22000000, "setControlPointOffset", 22, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "setMaxSpeedCartesian")) {

    _0RL_cd_e5cc9767023e3fa4_32000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_42000000, "setMaxSpeedCartesian", 21, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "setMaxSpeedJoint")) {

    _0RL_cd_e5cc9767023e3fa4_52000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_62000000, "setMaxSpeedJoint", 17, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "setMinAccelTimeCartesian")) {

    _0RL_cd_e5cc9767023e3fa4_d1000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_72000000, "setMinAccelTimeCartesian", 25, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "setMinAccelTimeJoint")) {

    _0RL_cd_e5cc9767023e3fa4_d1000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_82000000, "setMinAccelTimeJoint", 21, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "setSoftLimitCartesian")) {

    _0RL_cd_e5cc9767023e3fa4_92000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_a2000000, "setSoftLimitCartesian", 22, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "setSpeedCartesian")) {

    _0RL_cd_e5cc9767023e3fa4_f0000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_b2000000, "setSpeedCartesian", 18, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "setSpeedJoint")) {

    _0RL_cd_e5cc9767023e3fa4_f0000000 _call_desc(_0RL_lcfn_e5cc9767023e3fa4_c2000000, "setSpeedJoint", 14, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
_impl_ManipulatorCommonInterface_Middle::_ptrToInterface(const char* id)
{
  if (id == ::ManipulatorCommonInterface_Middle::_PD_repoId)
    return (::_impl_ManipulatorCommonInterface_Middle*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::ManipulatorCommonInterface_Middle::_PD_repoId))
    return (::_impl_ManipulatorCommonInterface_Middle*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
_impl_ManipulatorCommonInterface_Middle::_mostDerivedRepoId()
{
  return ::ManipulatorCommonInterface_Middle::_PD_repoId;
}

POA_ManipulatorCommonInterface_Middle::~POA_ManipulatorCommonInterface_Middle() {}

